### PR TITLE
Delete protoc-gen-validate

### PR DESCRIPTION
**Pull request by meteorcloudy**
protoc-gen-validate should just be protobuf's internal dependencies and not be checked into the BCR.

### CODE REVIEW

**Comment by fmeum** [comment]
In case it matters: `protoc-gen-validate` should be easy to get with `gazelle`.

**Review by Wyverald — APPROVED** [review]

**Comment by Wyverald** [comment]
we might need to manually delete these files from the mirror?

**Comment by meteorcloudy** [comment]
> In case it matters: protoc-gen-validate should be easy to get with gazelle.

Interesting, I'm just loading grpc's dependencies with a module extension. How does it look like with gazelle? (I thought it's only for go?)

 > we might need to manually delete these files from the mirror?

Yes, I'll do it.

**Comment by Kernald** [comment]
> protoc-gen-validate should just be protobuf's internal dependencies

Would you mind elaborating a bit on that? As someone not familiar with the whole Go ecosystem (nor Gazelle), with https://github.com/envoyproxy/protoc-gen-validate/issues/636 being an issue as well, I was happy to see pgv here before seeing this PR...

**Pull request merged**
