### PR TITLE
Fix "websocketpp" on Mac OS X.

### PR DESCRIPTION
**Pull request by BYVoid**
This change fixes the build on Mac OS X. According to the original CMakeLists.txt, "rt" is not linked on Mac OS X.

        if (NOT APPLE)
            set (WEBSOCKETPP_PLATFORM_LIBS pthread rt)
        else()
            set (WEBSOCKETPP_PLATFORM_LIBS pthread)
        endif()

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (websocketpp) have been updated in this PR. Please review the changes.

**Comment by Wyverald** [comment]
Existing versions cannot be changed on BCR. Please create a new version with a `.bcr.<N>` suffix (so `0.8.2.bcr.1` here).

**Comment by BYVoid** [comment]
Created `0.8.2.bcr.1` instead.

**Comment by meteorcloudy** [comment]
Please add the new version to https://github.com/bazelbuild/bazel-central-registry/blob/main/modules/websocketpp/metadata.json#L13

**Comment by meteorcloudy** [comment]
@BYVoid And can you please sign the Google CLA.

**Review by meteorcloudy — APPROVED** [review]

**Pull request merged**
