### PR TITLE
Add pybind11_bazel release 2.12.0.

### PR DESCRIPTION
**Pull request by junyer**

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @rwgk, modules you maintain (pybind11_bazel) have been updated in this PR. Please review the changes.

**Review by rwgk — APPROVED** [review]

**Comment by rwgk** [comment]
My approval doesn't seem to unblock merging?

**Comment by junyer** [comment]
> My approval doesn't seem to unblock merging?

Not yet, evidently, but hopefully in the not too distant future!

**Review by bazel-io — APPROVED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Pull request merged**
