### PR TITLE
Add rpmpack to the BCR repository.

### PR DESCRIPTION
**Pull request by jarondl**

### CODE REVIEW

**Comment by meteorcloudy** [comment]
@jarondl Can you please address the presubmit failures?

**Comment by keith** [comment]
I took this PR and submitted a new version with minor fixes to fix CI, please check it out! https://github.com/bazelbuild/bazel-central-registry/pull/1658

**Comment by alexeagle** [comment]
Random drive-by comment - on rules_oci we HAVE to test docker on Macos so we have a Testcontainers API key to get a remote docker daemon

**Comment by jarondl** [comment]
Thank you @keith ! that's super awesome.

**Pull request closed without merging**
