### PR TITLE
Yank zlib 1.2.12

### PR DESCRIPTION
**Pull request by meteorcloudy**
Due to https://github.com/advisories/GHSA-cfmr-vrgj-vqwv

### CODE REVIEW

**Review by fmeum — APPROVED** [review]

**Comment by meteorcloudy** [comment]
Please don't merge right now

**Comment by fmeum** [comment]
@meteorcloudy I generally only merge after approving if the PR author doesn't have write permissions themselves.

**Comment by meteorcloudy** [comment]
Got it, sounds good!

**Comment by meteorcloudy** [comment]
Not sure why the presubmit is blocked, close and reopen this PR to retry

**Pull request merged**
