### PR TITLE
Add swift_argument_parser

### PR DESCRIPTION
**Pull request by keith**

### CODE REVIEW

**Comment by fmeum** [comment]
@keith CI is failing. Should the runners be using macOS 13.0 to be useful?

**Review by alexeagle — COMMENTED** [review]
Would this module still be needed if there was a repository rule that could fetch arbitrary swift packages? Or is this used by the repository rule itself, and therefore is a special bootstrap case?

**Comment by keith** [comment]
added the flag to pick a newer version, hopefully that works. newer runners would probably work too although i forget how bazel picks the default version.

this wouldn't be needed if there was an arbitrary rule for that no, but given the discussion in the slack thread I figured i'd submit these

**Review by fmeum — APPROVED** [review]

**Comment by meteorcloudy** [comment]
LGTM after reading the slack thread.

**Pull request merged**
