### PR TITLE
grpc 1.66.0: Add current_py_cc_libs to pyx_library

### PR DESCRIPTION
**Pull request by mbland**
Fixes grpc/grpc#37251.

Fixes the following error, reproduced using
https://gist.github.com/mbland/f6d91ac30b074e16b76686d15ee4919d.

```txt
$ bazel build //...

[ ...snip... ]

ERROR: .../external/grpc~/src/python/grpcio/grpc/_cython/BUILD.bazel:25:12:
  Linking external/grpc~/src/python/grpcio/grpc/_cython/cygrpc.so failed:
  (Exit 1): cc_wrapper.sh failed: error executing CppLink command
    (from target @@grpc~//src/python/grpcio/grpc/_cython:cygrpc.so)
      external/bazel_tools~cc_configure_extension~local_config_cc/cc_wrapper.sh
      @bazel-out/darwin_arm64-fastbuild/bin/external/grpc~/src/python/grpcio/grpc/_cython/cygrpc.so-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Undefined symbols for architecture arm64:
  "_PyArg_UnpackTuple", referenced from:
      __Pyx_Coroutine_Throw(_object*, _object*) in cygrpc.o
      __Pyx_async_gen_athrow_send(__pyx_PyAsyncGenAThrow*, _object*) in cygrpc.o
```

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (grpc) have been updated in this PR. Please review the changes.

**Comment by mbland** [comment]
Hmm, so it appears I may need to refactor this into a new module release instead? That would make sense.

**Comment by Wyverald** [comment]
Yes -- you can submit this as version `1.66.0.bcr.1` (see https://github.com/bazelbuild/bazel-central-registry/blob/main/docs/README.md#versions-format)

**Comment by mbland** [comment]
Thanks, done. The failing checks now are for the download URL, but the [grpc/grpc releases](https://github.com/grpc/grpc/releases) don't appear to use the new URLs.

There _is_ a 1.66.1 release out now. If preferable, I can try to update this patch to add 1.66.1 to the BCR instead.

Either way, the diff now is:

```diff
diff -uNr 1.66.0/patches/adopt_bzlmod.patch 1.66.0.bcr.1/patches/adopt_bzlmod.patch
--- 1.66.0/patches/adopt_bzlmod.patch	2024-08-28 09:11:55
+++ 1.66.0.bcr.1/patches/adopt_bzlmod.patch	2024-08-28 09:11:01
@@ -1,13 +1,16 @@
 diff --git a/bazel/cython_library.bzl b/bazel/cython_library.bzl
-index dc2ef7a890..fd2881ed8c 100644
+index dc2ef7a890..93e99962db 100644
 --- a/bazel/cython_library.bzl
 +++ b/bazel/cython_library.bzl
-@@ -72,7 +72,7 @@ def pyx_library(name, deps = [], py_deps = [], srcs = [], **kwargs):
+@@ -72,7 +72,10 @@ def pyx_library(name, deps = [], py_deps = [], srcs = [], **kwargs):
          native.cc_binary(
              name = shared_object_name,
              srcs = [stem + ".cpp"],
 -            deps = deps + ["@local_config_python//:python_headers"],
-+            deps = deps + ["@rules_python//python/cc:current_py_cc_headers"],
++            deps = deps + [
++                "@rules_python//python/cc:current_py_cc_headers",
++                "@rules_python//python/cc:current_py_cc_libs",
++            ],
              defines = defines,
              linkshared = 1,
          )
diff -uNr 1.66.0/source.json 1.66.0.bcr.1/source.json
--- 1.66.0/source.json	2024-08-28 09:11:55
+++ 1.66.0.bcr.1/source.json	2024-08-28 09:11:01
@@ -5,7 +5,7 @@
     "patch_strip": 1,
     "patches": {
         "add_module_bazel.patch": "sha256-C3eqO1Vvq/N+4ZSRrz602t49jyFCrTgY0uk4MavK01k=",
-        "adopt_bzlmod.patch": "sha256-aNySqiYUkIeuzGyB02CDsU3KeMrFUKoZMX9cu1VEZSg=",
+        "adopt_bzlmod.patch": "sha256-MDnmY+E1X46kwsvKb7WHq7IiZxYrkK692XFtFTsLChE=",
         "disable-layering-check.patch": "sha256-/QbrEMxke9gUgbFjpMTKEk3y1NGk/56CeyWQgl6JEWI="
     }
 }
```

**Review by Wyverald — APPROVED** [review]

**Pull request merged**
