### PR TITLE
libconfig@1.7.3 (#2455)

### PR DESCRIPTION
**Pull request by dmitry-j-mikhin**
PR for #2455

Release: https://github.com/hyperrealm/libconfig/releases/tag/v1.7.3

Used by:
* https://github.com/kubevirt/kubevirt
* https://github.com/JFreegman/toxic

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (libconfig) have been updated in this PR. Please review the changes.

**Comment by meteorcloudy** [comment]
Please check the presubmit

**Comment by dmitry-j-mikhin** [comment]
Thanks, will try to fix

**Comment by dmitry-j-mikhin** [comment]
@meteorcloudy I added an experimental fix, can't test it now because I don't have access to the Windows VM. But it looks like the additional defines should fix compilation errors on Windows.

**Review by meteorcloudy — APPROVED** [review]
Thanks!

**Pull request merged**
