### PR TITLE
Add rules_kustomize@0.2.0

### PR DESCRIPTION
**Pull request by seh**
Impound Bazel rules for [the Kubernetes-related _kustomize_ tool](https://kubectl.docs.kubernetes.io/references/kustomize/) defined in [the _bisontrails/rules_kustomize_ GitHub repository](https://github.com/bisontrails/rules_kustomize).

### CODE REVIEW

**Comment by fmeum** [comment]
I triggered the pipeline, it fails with what looks like real issues.

Given that there is another `rules_kustomize` repo on GitHub, it may be clearer if you could add a prefix (e.g. org name) to the module name.

**Comment by seh** [comment]
> I triggered the pipeline, it fails with what looks like real issues.

Based on my fumbling but persistent effort [chronicled in the "bzlmod" channel of the "Bazel" Slack workspace](https://bazelbuild.slack.com/archives/C014RARENH0/p1673398098775519?thread_ts=1672165248.248799&cid=C014RARENH0), I think that I fixed those problems.

> Given that there is another `rules_kustomize` repo on GitHub, it may be clearer if you could add a prefix (e.g. org name) to the module name.

I do see a few other _rules_kustomize_ GitHub repositories. None of them have _MODULE.bazel_ files yet. @Wyverald had [mentioned in Slack discussion](https://bazelbuild.slack.com/archives/C014RARENH0/p1673297153167999?thread_ts=1672165248.248799&cid=C014RARENH0)  that he thought that claiming _rules_kustomize_ for my repository was acceptable. How should we proceed here? Should I prefix my module name with "bisontralis_?" Should I poll the authors of the other few repositories to learn whether any of them intend to submit their repositories to the BCR?

**Comment by seh** [comment]
The CI failure in the test module is due to not running with the `--experimental_use_sandboxfs` flag enabled. I may be able to work around that in my own configuration of _kustomize_, just for this module, unless there's a way that I can request additional flags be used for how we run _bazel_ here.

**Comment by fmeum** [comment]
CI is failing with what looks like a real "non-Bzlmod" error.

Given that there aren't any rules about who can name what in which way, I don't see a problem with this just being called `rules_kustomize`. After all, distinguishing `rules_kustomize` from `X_rules_kustomize` isn't much harder than doing the same for `X_rules_kustomize` and `Y_rules_kustomize`.

**Comment by seh** [comment]
> Does the ruleset itself require `--experimental_sandbox_fs` or is that just required for the tests? Given that this is one of the more arcane flags, getting this to work without it could make the module more generally useful.

It's not strictly required, but it helps. I documented the considerations in [the "Bazel's Sandbox and Load Restrictors" section of the repository documentation](https://github.com/bisontrails/rules_kustomize/blob/main/README.rst#bazel-s-sandbox-and-load-restrictors). If any of the information I offer there is now obsolete, since it's been over a year and a half since I wrote it, I'd like to update it.

I'll consider how best to accommodate the need in the CI workflow, and post an update either later today or tomorrow.

**Comment by seh** [comment]
> I'll consider how best to accommodate the need in the CI workflow, and post an update either later today or tomorrow.

I decided to specify the "build_flags" and "test_flags" fields in the _presubmit.yml_ file. If you find that sufficiently distasteful, I can instead change the "load restrictor" that _kustomize_ uses, making it more liberal such that it will accept symlinked files.

**Comment by alexeagle** [comment]
As much as I love to be a namespace purist and a "land grab" for shorter names is contentious (I'll probably be sad if someone takes "rules_js") I can also see a case that the better maintained or more widely used rulesets will more likely have someone to write the MODUlE.Bazel and any needed extensions.

**Comment by Wyverald** [comment]
My take is that this one is fine as it's not super high profile. As Alex said, I'd be much more careful giving away names like "rules_js".

**Comment by seh** [comment]
After much discussion with @fmeum in Slack (on [_execroot_ layout](https://bazelbuild.slack.com/archives/C014RARENH0/p1673545004486879?thread_ts=1672165248.248799&cid=C014RARENH0), [repository mapping](https://bazelbuild.slack.com/archives/C014RARENH0/p1673642747626029), [runfiles](https://bazelbuild.slack.com/archives/CDCMRLS23/p1673638422672719), [`rlocationpath`](https://bazelbuild.slack.com/archives/CDCMRLS23/p1674078669014879), and  [`rlocation`](https://bazelbuild.slack.com/archives/C014RARENH0/p1674160715619479)), borrowing from bazelbuild/bazel#17279 ahead of the next Bazel release, I think this patch will make it further through the CI workflow.

**Comment by seh** [comment]
See bazelbuild/continuous-integration#1536 for the cause of the file permissions problems (lost executable bit).

**Comment by seh** [comment]
In order to work around bazelbuild/continuous-integration#1536, I switched from using ZIP archive to a Tar archive of the GitHub-hosted repository.

I don't expect the Windows tests to pass yet, as I still have to figure out how to handle runfiles on Windows.

**Comment by alexeagle** [comment]
@seh not a blocker for this PR - I don't remember in the many long threads on this, whether we discussed just shipping a source archive of the repo like most other rulesets. https://github.com/bazel-contrib/rules-template for example - then you wouldn't have to struggle with the archive format and it would probably simplify things for you.

**Review by fmeum — APPROVED** [review]

**Pull request merged**
