### PR TITLE
Add lmdb 0.9.29

### PR DESCRIPTION
**Pull request by GZGavinZhao**

### CODE REVIEW

**Comment by keith** [comment]
windows failures here look real

**Comment by GZGavinZhao** [comment]
Oops, sorry, I think at the time of the original commit I hadn't learned about Platforms yet so just forgot about it after getting stuck :P

The Windows build is failing because of some command-line utilities provided by `lmdb`, which are not supported on non-Linux systems, so I added the `target_compatible_with` constraint.

**Comment by keith** [comment]
re-ran CI, you'll have to add the platforms dep to the MODULE.bazel

**Comment by keith** [comment]
failure, might need a rebase?

**Comment by GZGavinZhao** [comment]
Yep, I'll do that now. By the way, is there a way to not build some targets on Windows using `presubmit.yml`? I only want to test building `@lmdb//:lmdb` on Windows.

**Comment by GZGavinZhao** [comment]
Ok so I mirrored the approach used in `fmt`'s [`presubmit.yml`](https://github.com/bazelbuild/bazel-central-registry/blob/main/modules/fmt/9.1.0/presubmit.yml). Please let me know if this is acceptable.

**Comment by keith** [comment]
seems fine, alternatively you could use a matrix for the non-windows platforms, but the result would be the same

**Comment by GZGavinZhao** [comment]
Sorry for the trouble. MacOS should only test `@lmdb//:lmdb` as well. This should be the final revision.

**Comment by keith** [comment]
Looks like we're green here, anything else before we merge?

**Comment by GZGavinZhao** [comment]
Nope, I believe we're all set :D

**Review by keith — APPROVED** [review]

**Comment by keith** [comment]
thanks!

**Comment by GZGavinZhao** [comment]
Thank you for your help!

**Pull request merged**
