### PR TITLE
Make cc_configure_extension dev_dependency in abseil-cpp and re2

### PR DESCRIPTION
**Pull request by meteorcloudy**
Only re2, abseil-cpp, blake3 are still using cc_configure_extension and blake3 already has it as a dev dependency.

Addressing: https://github.com/bazelbuild/bazel/issues/24426

I will also send proper fixes to re2 and abseil-cpp, but it will take some time to get into a release.

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @derekmauro, modules you maintain (abseil-cpp) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @junyer, modules you maintain (re2) have been updated in this PR. Please review the changes.

**Comment by SanjayVas** [comment]
Note that googletest is depending on the bad re2 version. Should `2024-07-02` be yanked in favor of `2024-07-02.bcr.1`?

**Comment by meteorcloudy** [comment]
@SanjayVas `2024-07-02` should still work with Bazel 7, right? If it's just for Bazel 8 compatibility, the root project can add `bazel_dep(name = "re2", version = "2024-07-02.bcr.1")` to bump its version, or we can have a new googletest version that bumps the re2 version.

**Pull request merged**
