### PR TITLE
feat: add boost filesystem, foreach, json, logic, math, multi_index, pfr, static_string, tti

### PR DESCRIPTION
**Pull request by wep21**
- as title
- need skip url stability check

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (boost.math) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (boost.math, boost.multi_index) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (boost.filesystem, boost.math, boost.multi_index) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (boost.filesystem, boost.logic, boost.math, boost.multi_index, boost.static_string) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (boost.filesystem, boost.json, boost.logic, boost.math, boost.multi_index, boost.static_string) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (boost.filesystem, boost.json, boost.logic, boost.math, boost.multi_index, boost.static_string, boost.tti) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (boost.filesystem, boost.foreach, boost.json, boost.logic, boost.math, boost.multi_index, boost.static_string, boost.tti) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (boost.filesystem, boost.foreach, boost.json, boost.logic, boost.math, boost.multi_index, boost.pfr, boost.static_string, boost.tti) have been updated in this PR. Please review the changes.

**Comment by fmeum** [comment]
CI has some real failures.

**Comment by wep21** [comment]
> CI has some real failures.

@fmeum fixed it.

**Pull request merged**
