### PR TITLE
Add rpmpack

### PR DESCRIPTION
**Pull request by keith**
Forked from https://github.com/bazelbuild/bazel-central-registry/pull/1484

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (rpmpack) have been updated in this PR. Please review the changes.

**Comment by keith** [comment]
maybe we shouldn't send that notice for draft PRs? i think it'll take some work to get this green and reviewable

**Comment by keith** [comment]
Very minor changes compared to the original PR, I fixed the targets in the presubmit.yml, added the missing strip_prefix in the source.json, and put the correct MODULE.bazel contents here since they are already setup correctly upstream

**Comment by meteorcloudy** [comment]
> maybe we shouldn't send that notice for draft PRs? 

Good point, I'll fix that.

**Review by meteorcloudy — APPROVED** [review]

**Pull request merged**
