### PR TITLE
Add srcs to tinyobjloader

### PR DESCRIPTION
**Pull request by shabanzd**
This PR adds srcs to the tinyobjloader module.

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (tinyobjloader) have been updated in this PR. Please review the changes.

**Comment by Vertexwahn** [comment]
Already published modules are not allowed to be modified. Introduce a new version.

**Comment by shabanzd** [comment]
> Already published modules are not allowed to be modified. Introduce a new version.
The reason I am changing on the existing module and not adding a new version of the module, is that the module version matches the cc lib version and it will be confusing if they diverge ... I think of this as a bug fix tbh, since I can't see how this could work without the `srcs` .. or am I missing something silly ? 😄

**Comment by shabanzd** [comment]
will create a new version

**Pull request closed without merging**
