### PR TITLE
nanopb@0.4.9.1

### PR DESCRIPTION
**Pull request by tpudlik**
@PetteriAimonen FYI, adding the new release to the BCR.

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @PetteriAimonen, modules you maintain (nanopb) have been updated in this PR. Please review the changes.

**Comment by PetteriAimonen** [comment]
@tpudlik I wonder if you should be the maintainer of the bazel module, considering I don't really have any knowledge of bazel. I can click "Approve" if it helps, but I wouldn't really know any better.

**Comment by tpudlik** [comment]
We're both listed as maintainers. I thought it would be appropriate to list you, too, since you're the author of nanopb!

I believe the workflow is that one of us _and_ the BCR-wide maintainers needs to approve a PR. So this is just FYI that the change is happening. I'm happy to own keeping the BCR up to date.

**Comment by tpudlik** [comment]
@PetteriAimonen actually, on reviewing other PRs, I think it's necessary for a module maintainer to review this PR, even though I (its author) am also a maintainer. Would you mind hitting the "Approve" button (assuming you approve)?

**Review by fmeum — APPROVED** [review]

**Pull request merged**
