### PR TITLE
Add eigen version from main.

### PR DESCRIPTION
**Pull request by feuerste**
Version 3.4.0 is 3 years old. This version pulls
in all the functionality added throughout the last years.

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (eigen) have been updated in this PR. Please review the changes.

**Comment by meteorcloudy** [comment]
The version format change is concerning, assuming there is a 3.5 coming out later, `20241125.0` is actually going to be considered as a newer verison.

**Comment by feuerste** [comment]
@meteorcloudy I wasn't sure myself how to version it. Do you have a better suggestion? 4.0 should come some time as well, but not much work is going on according to https://gitlab.com/libeigen/eigen/-/issues/2699.

**Comment by meteorcloudy** [comment]
Indeed, it's a bit tricky, but to be future proof, maybe we can use something like: `3.4.0.20241125`? So that it will be the current latest version, but if 3.5.0 or 4.0 come out, it will not mess up the order. If we are sure the next version is going to be `4.0.0`, then we can also use `4.0.0-20241125` to indicate this is a pre-release of 4.0.

**Review by meteorcloudy — DISMISSED** [review]

**Comment by meteorcloudy** [comment]
Please also fix the directory name

**Review by meteorcloudy — APPROVED** [review]

**Comment by feuerste** [comment]
Thanks for your review and suggestions @meteorcloudy !

**Comment by meteorcloudy** [comment]
Np, one more fix needed ;)
```
BcrValidationResult.FAILED: The patch file `modules/eigen/4.0.0-20241125/patches/module_dot_bazel.patch` has expected integrity value `sha256-Q9fpY+Y/Z8x2bvDlfI9onJe9FDPF4PkfQxCBvqBmKDk=`, but the real integrity value is `sha256-4R/Q+wbTHHJpkHeb5Ox2wLjIpbqhbnIc9gvfve8FAbA=`.
```

**Review by meteorcloudy — APPROVED** [review]

**Comment by jwnimmer-tri** [comment]
This should have been named something like `3.4.90.20241125`.  On the [master development branch](https://github.com/eigen-mirror/eigen/blob/c458d68fae4bdce9b047ba9c4ba4379372b56970/Eigen/src/Core/util/Macros.h#L20-L22), Eigen currently self-identifies as `3.4.90`.  Calling this snapshot "4.0" was a mistake, since the next Eigen release will be named 3.5.

**Comment by lalten** [comment]
> This should have been named something like `3.4.90.20241125`. On the [master development branch](https://github.com/eigen-mirror/eigen/blob/c458d68fae4bdce9b047ba9c4ba4379372b56970/Eigen/src/Core/util/Macros.h#L20-L22), Eigen currently self-identifies as `3.4.90`. Calling this snapshot "4.0" was a mistake, since the next Eigen release will be named 3.5.

Looks like we got lucky (?) and they did change the version scheme with 5.0.0: https://gitlab.com/libeigen/eigen/-/releases/5.0.0
image


--> https://github.com/bazelbuild/bazel-central-registry/pull/6006

**Pull request merged**
