### PR TITLE
Add protobuf v24.4

### PR DESCRIPTION
**Pull request by armandomontanez**
Adds support for protobuf v24.4.

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @zhangskz, @mkruskal-google, @googleberg, modules you maintain (protobuf) have been updated in this PR. Please review the changes.

**Comment by mering** [comment]
@armandomontanez could you please add a `presubmit.yml` file?

**Comment by armandomontanez** [comment]
Should be ready for another look.

**Comment by zhangskz** [comment]
Note protobuf v24.4 is out-of-support and predates protobuf bzlmod support added in v27.x, so maintenance from protobuf team here is likely just best-effort.

**Comment by mering** [comment]
> Note protobuf v24.4 is out-of-support and predates protobuf bzlmod support added in v27.x, so maintenance from protobuf team here is likely just best-effort.

It is still highly wanted as this is the last version before Python support broke in Bzlmod. I tested it with our code base which is still stuck on v23 and it is a seamless upgrade there.

**Comment by armandomontanez** [comment]
I was hoping to contribute this as a very useful stepping stone for folks looking to start using bzlmod. Right now my team has to specify `--noenable_bzlmod`  in our `.bazelrc` because just turning on bzlmod breaks stuff. Getting this version of Protobuf in is the first step in migrating to bzlmod; being able to enable bzlmod at all without making Bazel choke. Upgrading Protobuf *first* is a non-starter because I'd have to migrate other projects to Bzlmod first and then get releases cut and then subsequently add those releases to the BCR.

**Review by fmeum — DISMISSED** [review]

**Comment by fmeum** [comment]
CI is failing due to a known issue with older rules_java versions. Updating it may fix this.

**Comment by armandomontanez** [comment]
Thanks for the pointer! :)

**Review by fmeum — APPROVED** [review]

**Pull request merged**
