### PR TITLE
Add rules_erlang 3.5.0

### PR DESCRIPTION
**Pull request by pjk25**
Add the latest release of rules_erlang https://github.com/rabbitmq/rules_erlang/releases/tag/3.5.0

### CODE REVIEW

**Review by fmeum — APPROVED** [review]

**Comment by fmeum** [comment]
@pjk25 Would you want to become the maintainer for the `rules_erlang` module? If so, you can add your contact info to `metadata.json`.

**Comment by pjk25** [comment]
> @pjk25 Would you want to become the maintainer for the `rules_erlang` module? If so, you can add your contact info to `metadata.json`.

I think I'm already listed?

**Comment by fmeum** [comment]
Sorry for the noise, the maintainer info was cut off in the diff and I didn't look at the full file.

**Comment by pjk25** [comment]
No problem, thanks for the quick approval and merge

**Pull request merged**
