### PR TITLE
feat: add `libarmgpuinfo@1.1.0+11140bec96`

### PR DESCRIPTION
**Pull request by mattyclarkson**
Uses an unstable archive at the moment. Will work with upstream to publish a stable archive for the next release.

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (libarmgpuinfo) have been updated in this PR. Please review the changes.

**Comment by mattyclarkson** [comment]
arm-software/libgpuinfo#15 raised to track adding a stable archive to the releases.

**Comment by meteorcloudy** [comment]
It would be nice if other patches could be upstreamed in the next version.

**Review by meteorcloudy — APPROVED** [review]

**Comment by mattyclarkson** [comment]
@meteorcloudy the following does not work:

```
$ cd $(mktemp -d)
$ cat <<EOF >MODULE.bazel
module(name = "demo")
bazel_dep(name = "libarmgpuinfo", version = "1.1.0+11140bec96")
EOF
$ bazel build @libarmgpuinfo
ERROR: Error computing the main repository mapping: module not found in registries: libarmgpuinfo@1.1.0
```

It seems the metadata part of the semantic version is being ignored (the `+` and after). Shall I file this as a bug?

**Comment by meteorcloudy** [comment]
Building metadata after `+` is ignored when doing version comparison according to https://bazel.build/external/module#version_format and https://semver.org/#spec-item-10, and after https://github.com/bazelbuild/bazel/issues/23127, it's actually impossible for Bzlmod to support this version format as `+` has a special meaning.

**Comment by meteorcloudy** [comment]
If we want this to work, we should have checked it in under `1.1.0` instead of `1.1.0+11140bec96`.

**Comment by mattyclarkson** [comment]
Understood, thanks for the explaination. Using it as `1.1.0` in `MODULE.bazel` makes sense.

**Pull request merged**
