### PR TITLE
Fix empty glob in boost.parameter .scope_exit .signals2

### PR DESCRIPTION
**Pull request by hofbi**
Needs skip-url-check

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @wep21, @Vertexwahn, modules you maintain (boost.parameter, boost.scope_exit, boost.signals2) have been updated in this PR. Please review the changes.

**Comment by Vertexwahn** [comment]
@bazel-io skip_check unstable_url

**Review by Vertexwahn — DISMISSED** [review]

**Review by bazel-io — DISMISSED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Comment by bazel-io** [comment]
Hello @wep21, @Vertexwahn, modules you maintain (boost.parameter, boost.scope_exit, boost.signals2, boost.variant) have been updated in this PR. Please review the changes.

**Review by wep21 — APPROVED** [review]

**Review by bazel-io — APPROVED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Pull request merged**
