### PR TITLE
Add marisa-trie 0.2.6.

### PR DESCRIPTION
**Pull request by BYVoid**

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (marisa-trie) have been updated in this PR. Please review the changes.

**Comment by BYVoid** [comment]
The following error seems a false alarm.

```
BcrValidationResult.FAILED: marisa-trie@0.2.6 is using an unstable source url: https://github.com/s-yata/marisa-trie/files/4832504/marisa-0.2.6.tar.gz.
You should use a release archive URL in the format of https://github.com/<ORGANIZATION>/<REPO>/releases/download/<version>/<name>.tar.gz to ensure the archive checksum stability.
```

https://github.com/s-yata/marisa-trie/files/4832504/marisa-0.2.6.tar.gz should be stable.

**Review by Wyverald — APPROVED** [review]

**Comment by meteorcloudy** [comment]
Just noticed the source URL of this module is `https://github.com/s-yata/marisa-trie/files/4832504/marisa-0.2.6.tar.gz`, which is a very unsafe URL since any users can upload a file to an issue comment and appears at a similar URL.

https://x.com/Ax_Sharma/status/1781706435115491409?t=bJfPTQOdy08PAmwg6H6H7w&s=19

We are going to put more checks for validation github urls in https://github.com/bazelbuild/bazel-central-registry/pull/3630. I think it's better to yank this module and use the source archive like `https://github.com/s-yata/marisa-trie/archive/refs/tags/v0.2.6.zip` instead.

**Pull request merged**
