### PR TITLE
feat: add fastdds a C++ implementation of the DDS

### PR DESCRIPTION
**Pull request by daohu527**
add fastdds a C++ implementation of the DDS (Data Distribution Service) standard

need `skip-url-stability-check`

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (fastdds) have been updated in this PR. Please review the changes.

**Review by meteorcloudy — DISMISSED** [review]

**Comment by daohu527** [comment]
MacArm will delete and not support

Windows error
```
(10:12:07) ERROR: C:/b/brtbcyf4/external/rules_foreign_cc~0.10.1/toolchains/BUILD.bazel:317:15: While resolving toolchains for target @rules_foreign_cc~0.10.1//toolchains:pkgconfig_tool_msvc_build_: invalid registered toolchain '@rules_foreign_cc//toolchains:preinstalled_nmake_toolchain': No repository visible as '@rules_foreign_cc' from main repository
```

seems the preinstalled_nmake_toolchain can't found?

**Comment by meteorcloudy** [comment]
Can you try add `bazel_dep(name = "rules_foreign_cc", version = "0.11.1")` as a dependency to bump its version? Maybe the issue is fixed in newer versions of rules_foreign_cc. /cc @jsharpe

**Comment by meteorcloudy** [comment]
@daohu527 Looks like the windows bug still exist in rules_foriegn_cc 0.11.1, can you please file an issue to the repo and we may have to disable windows test for now.

**Comment by daohu527** [comment]
@meteorcloudy sure, I will add a issue and disable the windows version first

**Review by meteorcloudy — APPROVED** [review]

**Pull request merged**
