### PR TITLE
Add boost.context@1.83.0.bcr.2 with required library sources.

### PR DESCRIPTION
**Pull request by benjaminp**

### CODE REVIEW

**Review by Vertexwahn — DISMISSED** [review]

**Review by bazel-io — DISMISSED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Comment by Vertexwahn** [comment]
@bazel-io skip_check unstable_url

**Comment by benjaminp** [comment]
@bazel-io skip_check unstable_url

**Review by Vertexwahn — DISMISSED** [review]

**Review by bazel-io — APPROVED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Comment by benjaminp** [comment]
Thanks for all the reviews. Sorry, it's complicated getting all the assembly to work on all platforms...

**Review by Wyverald — APPROVED** [review]

**Pull request merged**
