### PR TITLE
Add zlib@1.3.1.bcr.3

### PR DESCRIPTION
**Pull request by Wyverald**
Fixes two things from 1.3.1.bcr.2:
- added missing visibility declaration in new alias target (see https://github.com/bazelbuild/bazel-central-registry/commit/152ddc48cb95f301d7ec6a1e7ed4dcee666a7e8c#r144633540)
- added proper quoting for the Batch copy command to avoid problems with the `+` character (see https://github.com/bazelbuild/bazel/issues/22865#issuecomment-2244065242)

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (zlib) have been updated in this PR. Please review the changes.

**Review by fmeum — APPROVED** [review]

**Comment by meteorcloudy** [comment]
We probably want to update zlib in https://cs.opensource.google/bazel/bazel/+/master:src/MODULE.tools;l=16?q=MODULE.tools&ss=bazel to this version before flipping that flag.

**Comment by ywmei-brt1** [comment]
This quoting change in zlib is breaking windows build with bazel 7.4.0

Our codebase builds good with bazel 7.1.1, and when I try to upgrade to bazel 7.4.0 today, the build break on Windows due to zlib@1.3.1.bcr.3, the error message is:

`The system cannot find the path specified.`

```
ERROR: C:/users/ywmei/_bazel_ywmei/nzc4sxqc/external/zlib~/BUILD.bazel:59:8: Executing genrule @@zlib~//:copy_public_headers failed: (Exit 1): cmd.exe failed: error executing Genrule command (from target @@zl
ib~//:copy_public_headers)
  cd /d C:/users/ywmei/_bazel_ywmei/nzc4sxqc/execroot/_main
  SET CGO_ENABLED=0
    SET MSYS=winsymlinks:nativestrict
    SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\bin;C:\Windows;C:\Windows\System32;C:\Windows\System32\WindowsPowerShell\v1.0;C:\msys64\mingw64\bin;C:\tools\msys64\mingw64
\bin;C:\Program Files\Git\cmd
    SET RUNFILES_MANIFEST_ONLY=1
  cmd.exe /S /E:ON /V:ON /D /c @copy /Y "external\zlib~\crc32.h" "bazel-out\x64_windows-opt\bin\external\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\deflate.h" "bazel-out\x64_windows-opt\bin\extern
al\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\gzguts.h" "bazel-out\x64_windows-opt\bin\external\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\inffast.h" "bazel-out\x64_windows-opt\bin\ext
ernal\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\inffixed.h" "bazel-out\x64_windows-opt\bin\external\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\inflate.h" "bazel-out\x64_windows-opt\bi
n\external\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\inftrees.h" "bazel-out\x64_windows-opt\bin\external\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\trees.h" "bazel-out\x64_windows-opt
\bin\external\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\zconf.h" "bazel-out\x64_windows-opt\bin\external\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\zlib.h" "bazel-out\x64_windows-opt\
bin\external\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\zutil.h" "bazel-out\x64_windows-opt\bin\external\zlib~\zlib\include\"  >NUL
# Configuration: 4e4e1e31d23f2e31ce56a50c4eec85d7b529f047d94c13f75edc1cb55fca1048
# Execution platform: //configs/windows/config:platform
The system cannot find the path specified. 
Target //internal/pkg/scandeps:scandeps failed to build

...
```

If I manually change this `copy_public_headers` rule in `C:\Users\ywmei\_bazel_ywmei\nzc4sxqc\external\zlib~\BUILD.bazel` back to zlib@1.3.1.bcr.2: `"@copy /Y $(location %s) $(@D)\\zlib\\include\\  >NUL"` The build is happy again. But since this is our transparent dependency (I don't even know how to figure out which our direct dependency is importing zlib@1.3.1.bcr.3....), I am not very sure how to fix our build. By any chance, if you have any idea that might be able to help me fix the build, please let me know.  Thank you very much.

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/74#019367db-94c1-4ad2-92ab-2594320b1a75 shows the windows build is working. 

Does this still reproduce with `--output_user_root=C:/b` as a startup option?

**Comment by ywmei-brt1** [comment]
> https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/74#019367db-94c1-4ad2-92ab-2594320b1a75 shows the windows build is working.
> 
> Does this still reproduce with `--output_user_root=C:/b` as a startup option?

I tried to add `--output_user_root=C:/b`, but it still broken due to `The system cannot find the path specified.` :


```
PS C:\src\re-client> bazelisk --output_user_root=C:/b build --verbose_failures --config=remotewin //internal/pkg/scandeps:scandeps 

...

ERROR: C:/b/nzc4sxqc/external/zlib~/BUILD.bazel:59:8: Executing genrule @@zlib~//:copy_public_headers failed: (Exit 1): cmd.exe failed: error executing Genrule command (from target @@zlib~//:copy_public_heade
rs)
  cd /d C:/b/nzc4sxqc/execroot/_main
  SET CGO_ENABLED=0
    SET MSYS=winsymlinks:nativestrict
    SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\tools\msys64\usr\bin;C:\tools\msys64\bin;C:\Windows;C:\Windows\System32;C:\Windows\System32\WindowsPowerShell\v1.0;C:\msys64\mingw64\bin;C:\tools\msys64\mingw64
\bin;C:\Program Files\Git\cmd
    SET RUNFILES_MANIFEST_ONLY=1
  cmd.exe /S /E:ON /V:ON /D /c @copy /Y "external\zlib~\crc32.h" "bazel-out\x64_windows-opt\bin\external\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\deflate.h" "bazel-out\x64_windows-opt\bin\extern
al\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\gzguts.h" "bazel-out\x64_windows-opt\bin\external\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\inffast.h" "bazel-out\x64_windows-opt\bin\ext
ernal\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\inffixed.h" "bazel-out\x64_windows-opt\bin\external\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\inflate.h" "bazel-out\x64_windows-opt\bi
n\external\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\inftrees.h" "bazel-out\x64_windows-opt\bin\external\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\trees.h" "bazel-out\x64_windows-opt
\bin\external\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\zconf.h" "bazel-out\x64_windows-opt\bin\external\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\zlib.h" "bazel-out\x64_windows-opt\
bin\external\zlib~\zlib\include\"  >NUL && @copy /Y "external\zlib~\zutil.h" "bazel-out\x64_windows-opt\bin\external\zlib~\zlib\include\"  >NUL
# Configuration: 4e4e1e31d23f2e31ce56a50c4eec85d7b529f047d94c13f75edc1cb55fca1048
# Execution platform: //configs/windows/config:platform
The system cannot find the path specified. 
Target //internal/pkg/scandeps:scandeps failed to build

```

I found a workaround that if I ping zlib version to 1.3.1.bcr.3 in our MODULE.bazel file, then use `single_version_override` to secretly patch it back to 1.3.1.bcr.2, then I am able to build on windows.


```
## In Module.bazel file, ping zlib version and patch it back to make windows build happy

bazel_dep(name = "zlib", version = "1.3.1.bcr.3", repo_name = "zlib")
single_version_override(
    module_name = "zlib",
    patch_strip = 0,
    patches = [
        "//third_party/patches/bazel:zlib.patch",
    ],
)
```

**Pull request merged**
