### PR TITLE
feat: add triton-inference-server-common.

### PR DESCRIPTION
**Pull request by ryanli**

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (triton-inference-server-common) have been updated in this PR. Please review the changes.

**Comment by ryanli** [comment]
The version `0.0.0-20240821-578491f` seems to be causing problems but I see [existing packages such as `googleapis` using this pattern](https://github.com/bazelbuild/bazel-central-registry/tree/main/modules/googleapis). Please advise how to proceed from here?

**Comment by meteorcloudy** [comment]
It's not the version number, it's the source url is unstable: https://blog.bazel.build/2023/02/15/github-archive-checksum.html

I've added a label to bypass this check.

**Review by meteorcloudy — APPROVED** [review]

**Comment by meteorcloudy** [comment]
presubmit failing on debian11

**Comment by ryanli** [comment]
> presubmit failing on debian11

There's some `-Wall` shenanigan going on in debian11 and the underlying issue has been fixed in the latest `protobuf` release (not available on BCR yet).

For now I've just removed debian from the testing matrix as it seems to be passing on both ubuntus and working locally for my debian12 setup. PTAL?

**Review by meteorcloudy — APPROVED** [review]

**Pull request merged**
