### PR TITLE
add magic_enum

### PR DESCRIPTION
**Pull request by zaucy**

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (magic_enum) have been updated in this PR. Please review the changes.

**Comment by lalten** [comment]
bump on this :) No clue about the Windows error, but for the Linux one you could try to (temporarily) patch in a higher `--experimental_ui_max_stdouterr_bytes` in the .bazelrc?
> stderr (/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/564d2f181201e0c9b383e74c8e273ef9/execroot/_main/bazel-out/_tmp/actions/stderr-10) 2099313 exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes

**Comment by dieortin** [comment]
Why is patching the `.bazelrc` needed? I thought only the one in the project root would apply, and not the ones in modules you depend on

**Comment by zaucy** [comment]
the presubmit seems to read it for example here: https://buildkite.com/bazel/bcr-presubmit/builds/5043#018f2bef-01c2-40ac-a4c6-8c9ff1401613/128-136

**Comment by meteorcloudy** [comment]
Looks like your `.bazelrc` file has CRLF line ending? Which doesn't match the patch file.
```
$ file .bazelrc
.bazelrc: ASCII text, with CRLF line terminators
```

Coverting to LF line ending could help with the windows failure.

**Comment by zaucy** [comment]
> Looks like your .bazelrc file has CRLF line ending?

Yeah it was a mistake. I've made a PR to clean that up. https://github.com/Neargye/magic_enum/pull/358

> Coverting to LF line ending could help with the windows failure.

For the patch file? In one of my previous commits in this PR I had the patch file using LF line endings and it failed https://buildkite.com/bazel/bcr-presubmit/builds/5038#018f2be4-1c33-4b6a-a0c9-3a29c6b62de1/147-180

I think what I'm going to do is just disable bazel `7.x` so that patching the flag doesn't matter and then in the next magic_enum release `7.x` can be added bazel.

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (magic_enum) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @mattyclarkson, modules you maintain (ape, rules_bzip2, rules_coreutils, rules_curl, rules_diff, rules_gzip, rules_squashfs, rules_zstd, toolchain_utils) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @alexeagle, modules you maintain (aspect_bazel_lib, aspect_rules_aws, aspect_rules_js, aspect_rules_lint, rules_buf, rules_oci, rules_proto, toolchains_protoc) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @kormide, modules you maintain (aspect_bazel_lib) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @CaerusKaru, modules you maintain (aspect_rules_aws) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @aspect-build, modules you maintain (aspect_rules_esbuild, aspect_rules_py, aspect_rules_rollup, aspect_rules_swc, aspect_rules_terser, rules_nodejs) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @gregmagolan, modules you maintain (aspect_rules_jasmine, aspect_rules_jest, aspect_rules_js, aspect_rules_ts, aspect_rules_webpack) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @jbedard, modules you maintain (aspect_rules_jasmine, aspect_rules_js, aspect_rules_ts) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @thesayyn, modules you maintain (aspect_rules_ts, rules_distroless, rules_oci, rules_proto) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @dzbarsky, modules you maintain (aws-in-a-box, libarchive, rules_itest) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @fmeum, modules you maintain (bazel_env.bzl, bazel_features, buildozer, gazelle, rules_fuzzing, rules_go, rules_jni) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Wyverald, @meteorcloudy, modules you maintain (bazel_features) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @comius, modules you maintain (bazel_skylib, bazel_skylib_gazelle_plugin) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @zetten, @adincebic, modules you maintain (bazel_sonarqube) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @sergeykhliustin, modules you maintain (bazelpods) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @agl, @bob-beck, @davidben, modules you maintain (boringssl) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @curoky, modules you maintain (catch2) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (catch2, cpuinfo, hypothesis, imath, libwebp, tinyformat) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @ewianda, @ColinHeathman, modules you maintain (com_github_benchsci_rules_nodejs_gazelle) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @illicitonion, modules you maintain (contrib_rules_jvm, rules_rust) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @gibfahn, @shs96c, modules you maintain (contrib_rules_jvm) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @martis42, modules you maintain (depend_on_what_you_use) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @linzhp, modules you maintain (gazelle, hermetic_cc_toolchain, rules_go) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @tyler-french, modules you maintain (gazelle, rules_go) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @calebzulawski, modules you maintain (gcem) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @sywhang, modules you maintain (hermetic_cc_toolchain) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @jan-wassenberg, @eustas, @rhettstucki, modules you maintain (highway) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @stonier, modules you maintain (maliput, maliput_malidrive) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @nicholasjng, modules you maintain (nanobind_bazel) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @inazarenko, modules you maintain (protobuf-matchers) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @zhangskz, @googleberg, modules you maintain (protobuf, rules_proto) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @mkruskal-google, modules you maintain (protobuf) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @frigus02, modules you maintain (pybind11_abseil, pybind11_protobuf) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @odygrd, modules you maintain (quill) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @junyer, modules you maintain (re2) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @QrczakMK, modules you maintain (riegeli) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @lalten, modules you maintain (rules_appimage) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @yuyawk, modules you maintain (rules_build_error) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @nya3jp, modules you maintain (rules_contest) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @seh, modules you maintain (rules_cue) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @matts1, modules you maintain (rules_directory) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @loosebazooka, modules you maintain (rules_distroless) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @abrisco, modules you maintain (rules_helm) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @luispadron, modules you maintain (rules_ios) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @hvadehra, modules you maintain (rules_java) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @oxidase, modules you maintain (rules_poetry) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @rickeylev, @f0rmiga, modules you maintain (rules_python, rules_python_gazelle_plugin) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @p0deje, modules you maintain (rules_ruby) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @UebelAndre, @scentini, modules you maintain (rules_rust) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @cgrindel, modules you maintain (rules_swift_package_manager) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @ihavespoons, modules you maintain (rules_syft) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @mark-thm, @theoremlp, modules you maintain (rules_uv) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @brentleyjones, @BalestraPatrick, modules you maintain (rules_xcodeproj) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Megakuul, modules you maintain (simplehttp) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @jpsim, modules you maintain (sourcekitten) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @keith, modules you maintain (sourcekitten, swift-syntax) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @zadlg, modules you maintain (tree-sitter-bazel) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @udaya2899, modules you maintain (versor) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (abseil-py, bazel_ci_rules, cctz, cel-spec, ceres-solver, civetweb, cli11, cpp-httplib, fp16, fxdiv, grpc-httpjson-transcoding, grpc, highs, jwt_verify_lib, libprotobuf-mutator, libzmq, magic_enum, opencensus-proto, proto-converter, protoc-gen-validate, pthreadpool, rules_pkl, ruy, scip, su-exec, tomlplusplus, xds) have been updated in this PR. Please review the changes.

**Comment by zaucy** [comment]
Very sorry everyone who just got pinged. I accidentally rebased against my fork and merged in a bunch of unrelated commits 😓

**Pull request closed without merging**
