### PR TITLE
Add envoy_api

### PR DESCRIPTION
**Pull request by mering**
- Based on https://github.com/envoyproxy/envoy/pull/34355
- Requires https://github.com/bazelbuild/bazel-central-registry/pull/3420 and https://github.com/bazelbuild/bazel-central-registry/pull/3423
- Upstreaming target name alignment in https://github.com/bazelbuild/bazel-central-registry/pull/3415 and https://github.com/envoyproxy/envoy/pull/37662
- Issue for patched Protobuf: https://github.com/envoyproxy/envoy/issues/37669

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (envoy_api) have been updated in this PR. Please review the changes.

**Comment by mering** [comment]
@bazel-io skip_check unstable_url

**Comment by mering** [comment]
@keith @meteorcloudy @fmeum could someone please unblock the CI? Thanks!

**Comment by mering** [comment]
@meteorcloudy could you PTAL? Thanks.

**Review by meteorcloudy — APPROVED** [review]

**Pull request merged**
