### PR TITLE
Support git_repository sources in BCR

### PR DESCRIPTION
**Pull request by armandomontanez**
Adds workarounds in the BCR validation script to properly support `git_repository` sources as a step forwards toward https://github.com/bazelbuild/bazel/issues/23461.

### CODE REVIEW

**Comment by meteorcloudy** [comment]
@fmeum @Wyverald Any concerns on supporting `git_repository` in BCR?

**Comment by fmeum** [comment]
Not in general, but we have to be careful about what kind of refs we allow. Tags can be changed retroactively, so if we want the lockfiles to actually lock down the contents, we would need to restrict this to commits (living with the fact that the hash is just SHA-1).

**Comment by meteorcloudy** [comment]
That's a really good point! @armandomontanez Can you please add such a check? Basically, verify `commit` is specified and matches a commit pattern.

**Comment by armandomontanez** [comment]
Good point, added a handful of checks/constraints to enforce this.

**Review by fmeum — APPROVED** [review]

**Review by meteorcloudy — APPROVED** [review]

**Pull request merged**
