### PR TITLE
Publish realm/SwiftLint@0.54.0

### PR DESCRIPTION
**Pull request by jpsim**
Release: https://github.com/realm/SwiftLint/releases/tag/0.54.0

### CODE REVIEW

**Review by Wyverald — APPROVED** [review]

**Comment by jpsim** [comment]
> /usr/bin/sudo /usr/bin/xcode-select --switch /Applications/Xcode14.2.app

The CI job failed because this version of SwiftLint requires Xcode 15.0 or later. Is there a way to specify this requirement in `presubmit.yml` or do the CI machines need to be updated?

**Comment by Wyverald** [comment]
cc @meteorcloudy @fweikert

**Comment by meteorcloudy** [comment]
Unfortunately not yet, I filed https://github.com/bazelbuild/continuous-integration/issues/1780 to track this.

**Comment by jpsim** [comment]
Thanks for filing that @meteorcloudy.

Would it be reasonable to comment out the macOS parts of the presubmit configuration for this release considering the Linux one is passing?

It would be nice to not have to block the availability of this SwiftLint release on the installation of Xcode 15 on CI.

**Comment by meteorcloudy** [comment]
OK, make senses. I assumed you have tested this locally? I'll ping this PR when Xcode 15 is installed and we can re-enable the test on macOS in the presubmit.yml later.

**Review by meteorcloudy — APPROVED** [review]

**Pull request merged**
