### PR TITLE
highway@1.1.0

### PR DESCRIPTION
**Pull request by mmorel-35**
Release: https://github.com/google/highway/releases/tag/1.1.0

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (highway) have been updated in this PR. Please review the changes.

**Comment by Wyverald** [comment]
Hmm. Have you contacted the maintainers? If the maintainers have set up the Publish to BCR app, we should prefer to use their automated PRs.

**Review by jan-wassenberg — APPROVED** [review]
Nice, thanks for adding Highway to BCR!

FYI the presubmit I had defined were untested starting points; what you have defined looks good to me.

**Comment by fmeum** [comment]
Thanks for the confirmation, I will merge this as is.

@jan-wassenberg I have to apply an exemption for an unstable source archive. Since you are the owner, would it be possible to start adding release archives to the GitHub releases? The auto-generated archives are not guaranteed to remain stable over time.

**Comment by jan-wassenberg** [comment]
We can certainly consider release archives. What exactly does that mean, and require?

**Comment by fmeum** [comment]
> We can certainly consider release archives. What exactly does that mean, and require?

You would have to manually (either in a GitHub action, locally via `git archive` or by reuploading the auto-generated source archives) create an archive containing all sources and add it as an artifact to the release, similar to how you add the `.asc` file today.

**Comment by fmeum** [comment]
@mmorel-35 CI is failing to find some test targets.

**Review by jan-wassenberg — APPROVED** [review]
LGTM :)

**Comment by jan-wassenberg** [comment]
Got it, we can run `git archive --prefix=highway-X.Y.Z/ -o highway-X.Y.Z.tar.gz vX.Y.Z`.

What's the issue with Bazel on Windows?

hwy_ops_tests is meant to be the collection of all tests. Is there a way we can make it visible outside Highway?

**Pull request merged**
