### PR TITLE
Add yams 5.1.0

### PR DESCRIPTION
**Pull request by jpsim**
Released here: https://github.com/jpsim/Yams/releases/tag/5.1.0

### CODE REVIEW

**Comment by jpsim** [comment]
I guess I need a maintainer to approve this:

```
BcrValidationResult.NEED_BCR_MAINTAINER_REVIEW: The presubmit.yml file of yams@5.1.0 doesn't match its previous version yams@5.0.6, the following presubmit.yml file change should be reviewed by a BCR maintainer.
    --- modules/yams/5.0.6/presubmit.yml
    +++ modules/yams/5.1.0/presubmit.yml
    @@ -9,7 +9,7 @@
         platform: ubuntu2004
         environment:
           CC: "clang"
    -      SWIFT_VERSION: "5.8.1"
    +      SWIFT_VERSION: "5.10"
           SWIFT_HOME: "$HOME/swift-$SWIFT_VERSION"
           PATH: "$PATH:$SWIFT_HOME/usr/bin"
         shell_commands: *shell_commands
```

**Comment by brentleyjones** [comment]
Btw you submitted here as well: https://github.com/bazelbuild/bazel-central-registry/pull/1679

**Comment by jpsim** [comment]
> Btw you submitted here as well: https://github.com/bazelbuild/bazel-central-registry/pull/1679

Ah I forgot this repo has the bot enabled. Some of my other modules don’t have that integration working.

**Comment by jpsim** [comment]
Can a BCR maintainer please trigger CI? Maybe @brentleyjones ?

**Review by brentleyjones — DISMISSED** [review]

**Comment by jpsim** [comment]
I think I need to make more changes upstream for Bazel 7.x support. For now I've updated the presubmit file to use Bazel 6.x.

**Comment by jpsim** [comment]
This needs another maintainer approval to run (sorry to bug @brentleyjones, but that seems to be the intended process here?)

**Review by fmeum — APPROVED** [review]

**Pull request merged**
