### PR TITLE
Add libgit2

### PR DESCRIPTION
**Pull request by zaucy**
based on my libgit2 PR: https://github.com/libgit2/libgit2/pull/6436

### CODE REVIEW

**Comment by alexeagle** [comment]
I suggest we wait a bit to see what the upstream maintainers say about your PR. It would be better for these files to be maintained there, so that changes to libgit2 which break the Bazel build will be noticed and fixed before someone tries to mirror a release to BCR.

To that end, it would also be good to include at least a minimal smoke test in the CI for that project.

**Comment by Vertexwahn** [comment]
Can we merge this?

**Comment by alexeagle** [comment]
It's okay with me, there is not a quality bar for this registry.
However the upstream maintainer gave some feedback

> That's the absolute worst-case scenario fallback code. Using it is going to be a huge perf hit.

**Comment by zaucy** [comment]
closed for now. see https://github.com/libgit2/libgit2/pull/6436#issuecomment-1987018499

**Pull request closed without merging**
