### PR TITLE
feat: add boost function, endian, function_types, unordered, type_index, winapi

### PR DESCRIPTION
**Pull request by wep21**
- add boost function, endian, function_types, unordered, type_index, winapi
- need skip url stability check
- closes https://github.com/bazelbuild/bazel-central-registry/pull/2579

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (boost.endian, boost.function, boost.function_types, boost.type_index, boost.unordered) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (boost.endian, boost.function, boost.function_types, boost.type_index, boost.unordered, boost.winapi) have been updated in this PR. Please review the changes.

**Comment by meteorcloudy** [comment]
@wep21 Please address the presubmit failure

**Comment by wep21** [comment]
@meteorcloudy I'm sorry, but I fixed the unordered error.

**Review by meteorcloudy — APPROVED** [review]

**Pull request merged**
