### PR TITLE
feat: update boost.tti, uuid

### PR DESCRIPTION
**Pull request by wep21**
- closes #2953

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.tti, boost.uuid) have been updated in this PR. Please review the changes.

**Comment by wep21** [comment]
@bazel-io skip_check unstable_url

**Review by Vertexwahn — APPROVED** [review]

**Review by bazel-io — APPROVED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Comment by wep21** [comment]
cc @meteorcloudy @fmeum

**Pull request merged**
