### PR TITLE
bazel_ci_rules@1.0.0

### PR DESCRIPTION
**Pull request by mmorel-35**
Release: https://github.com/bazelbuild/continuous-integration/releases/tag/rules-1.0.0

Used by:
* https://github.com/bazelbuild/rules_rust

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (bazel_ci_rules) have been updated in this PR. Please review the changes.

**Comment by fmeum** [comment]
Let's wait for the Bazel team to say whether they want this to be a module or not (and in which form).

@Wyverald

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (bazel_ci_rules) have been updated in this PR. Please review the changes.

**Comment by meteorcloudy** [comment]
@coeuvre Do we need the bazel ci rules to be a BCR module?

**Comment by meteorcloudy** [comment]
https://github.com/bazelbuild/rules_rust/blob/dc08bde7a83d882539a08cffa844854d564204b8/examples/crate_universe/WORKSPACE.bazel#L731-L739

Looks like it ships a repo rule, so it probably makes sense for it to be a BCR module.

**Review by meteorcloudy — APPROVED** [review]
I'm merging this one since it makes the remote execution setup easier for Bazel CI users.

**Pull request merged**
