### PR TITLE
add highs@1.8.1

### PR DESCRIPTION
**Pull request by lperron**
Here is the support for highs 1.8.1

Please add the tag for unstable ref.

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (highs) have been updated in this PR. Please review the changes.

**Comment by Vertexwahn** [comment]
@bazel-io skip_check unstable_url

**Comment by Wyverald** [comment]
please fix the check failures.

**Comment by lperron** [comment]
Done
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le lun. 25 nov. 2024 à 21:02, Xùdōng Yáng ***@***.***> a
écrit :

**Review by Wyverald — APPROVED** [review]

**Pull request merged**
