### PR TITLE
rules_pkl@0.2.0

### PR DESCRIPTION
**Pull request by shs96c**
These rules make using [Pkl](https://pkl-lang.org) a pleasure with Bazel.

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (rules_pkl) have been updated in this PR. Please review the changes.

**Review by holzensp — DISMISSED** [review]

**Comment by bazel-io** [comment]
Hello @holzensp, modules you maintain (rules_pkl) have been updated in this PR. Please review the changes.

**Review by holzensp — APPROVED** [review]
Quite the rabbit hole of nits

**Comment by bazel-io** [comment]
Hello @holzensp, @sitaktif, @KushalP, modules you maintain (rules_pkl) have been updated in this PR. Please review the changes.

**Review by fmeum — APPROVED** [review]

**Pull request merged**
