### PR TITLE
Improve opentelemetry-proto

### PR DESCRIPTION
**Pull request by mering**
Add Python and Go proto bindings

### CODE REVIEW

**Comment by mering** [comment]
@bazel-io skip_check unstable_url

**Comment by bazel-io** [comment]
Hello @keith, modules you maintain (opentelemetry-proto) have been updated in this PR. Please review the changes.

**Review by keith — APPROVED** [review]

**Comment by keith** [comment]
ci issue

**Comment by mering** [comment]
@keith can you trigger the CI again please?

**Comment by mering** [comment]
@keith same here, one more time please.

**Comment by keith** [comment]
done

**Comment by mering** [comment]
@keith again please? Thx.

**Review by keith — APPROVED** [review]

**Pull request merged**
