### PR TITLE
Add status_macros v0.0.1

### PR DESCRIPTION
**Pull request by jimrogerz**
A module that includes RETURN_IF_ERROR and ASSIGN_OR_RETURN macros common in Google C++.

### CODE REVIEW

**Comment by fmeum** [comment]
These macros seem very useful on their own, thanks for the submission!

From looking into https://github.com/jimrogerz/status_macros/blob/1592ab2d4b4f92976fc3f4a6cb3a1323a4b549c3/status_macros.h#L23 and https://github.com/jimrogerz/status_macros/blob/1592ab2d4b4f92976fc3f4a6cb3a1323a4b549c3/status_builder.cc#L24, could this interact badly with builds that also include MediaPipe, e.g. due to ODR violations?

**Comment by jimrogerz** [comment]
Hi Fabian, good callout because I have not done any renaming. There won't be any header conflicts because I copied source from the [internal package](https://github.com/google/mediapipe/blob/460346ed131aad914087c6bd1e1c7d855abe583d/mediapipe/framework/deps/BUILD#L276).  I'm not sure if there could be issues with multiple implementations, but I did my best to test by making some changes in the mediapipe repo:

```
#WORKSPACE
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "status_macros",
    commit = "1592ab2d4b4f92976fc3f4a6cb3a1323a4b549c3",
    remote = "https://github.com/jimrogerz/status_macros.git",
)
```

```
#BUILD.bazel
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        "@status_macros//:status_macros",
        "//mediapipe/framework/port:status",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
    ],
)
```

```cpp
// main.cc
#include <iostream>

#include "absl/status/status.h"
#include "absl/status/statusor.h"
#include "mediapipe/framework/port/status_macros.h"
#include "status_macros.h"

absl::Status DoSomething() { return absl::OkStatus(); }

absl::StatusOr<int> GetSomething() {
  RETURN_IF_ERROR(DoSomething());
  return 1;
}

absl::Status CallGetSomething() {
  ASSIGN_OR_RETURN(auto result, GetSomething());
  return absl::OkStatus();
}

int main(int argc, char **argv) {
  std::cout << CallGetSomething() << std::endl;
}
```

```sh
INFO: Analyzed target //:main (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:main up-to-date:
  bazel-bin/main
INFO: Elapsed time: 0.063s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/main
OK
```

**Comment by Wyverald** [comment]
I think this should be filed under a slightly less generic name (maybe cpp_status_macros). Would that be tenable?

**Comment by alexeagle** [comment]
+1 to @Wyverald - as a bazel user I'd expect this to be Bazel macros for dealing with Bazel's status files (stable-status.txt and volatile-status.txt)

**Comment by jimrogerz** [comment]
Relevant discussion: https://github.com/abseil/abseil-cpp/issues/976

**Pull request closed without merging**
