### PR TITLE
toolchains_arm_gnu@0.0.1

### PR DESCRIPTION
**Pull request by hexdae**
Release: https://github.com/hexdae/bazel-arm-none-eabi/releases/tag/v0.0.1

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (arm_gnu_toolchain) have been updated in this PR. Please review the changes.

**Comment by hexdae** [comment]
This should be ready to review, it adds some ARM cross compilation toolchains.

CC: @AmateurECE

**Comment by alexeagle** [comment]
There are a couple other modules using a naming scheme "toolchains_*" wdyt about following that?

**Comment by hexdae** [comment]
Hey @alexeagle, thanks for the suggestion, let's go with that. I'll make the changes

I also have [RISCV](https://github.com/hexdae/bazel-riscv-none-elf) project I'm thinking about publishing soon that will benefit from uniform naming conventions.

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (toolchains_arm_gnu) have been updated in this PR. Please review the changes.

**Comment by hexdae** [comment]
@alexeagle This should be ready

**Review by meteorcloudy — APPROVED** [review]

**Pull request merged**
