### PR TITLE
Add libarchive 3.7.4

### PR DESCRIPTION
**Pull request by keith**
This patch is almost the same as 3.7.2.bcr except part of the patch was
removed for compat with this commit:

https://github.com/libarchive/libarchive/commit/616c7dca2ba7e11436f1c49f366f1fae7071d21e

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @dzbarsky, modules you maintain (libarchive) have been updated in this PR. Please review the changes.

**Comment by keith** [comment]
open question is do i need to re-apply the logic of that LA_DEAD patch to the new name

**Comment by zaucy** [comment]
can we collaborate with the patches done in https://github.com/bazelbuild/bazel-central-registry/pull/1916 as well? I would love to have Windows support for libarchive in the BCR and the tests to ensure it's working.

**Comment by dzbarsky** [comment]
> open question is do i need to re-apply the logic of that LA_DEAD patch to the new name

I think I had to add that patch to get it compiling (at least with the zig_cc toolchain). I suppose if it compiles without it, we can drop the patch.

> can we collaborate with the patches done in #1916 as well? I would love to have Windows support for libarchive in the BCR and the tests to ensure it's working.

+1

**Review by dzbarsky — APPROVED** [review]

**Review by bazel-io — APPROVED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Pull request merged**
