### PR TITLE
protobuf@28.1

### PR DESCRIPTION
**Pull request by zhangskz**
Release: https://github.com/protocolbuffers/protobuf/releases/tag/v28.1

*Manual BCR release **NOT** automated by [Publish to BCR](https://github.com/apps/publish-to-bcr) due to problem at time of v28.1 release.*

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @mkruskal-google, @googleberg, modules you maintain (protobuf) have been updated in this PR. Please review the changes.

**Review by mkruskal-google — APPROVED** [review]

**Review by bazel-io — APPROVED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Comment by honnix** [comment]
Sorry for commenting in this PR. What is the reason there is no any 25 release in BCR?

**Comment by zhangskz** [comment]
Hi, in general a github issue would be prefferrable for future inquiries! 25.x predates Protobuf's support in BCR and supports WORKSPACE instead.

**Comment by honnix** [comment]
> Hi, in general a github issue would be prefferrable for future inquiries! 25.x predates Protobuf's support in BCR and supports WORKSPACE instead.

Thank you. I can move the conversation into an issue.

**Comment by honnix** [comment]
For the record #2897

**Pull request merged**
