### PR TITLE
feat: update boost.geometry

### PR DESCRIPTION
**Pull request by wep21**
- as title

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.compatibility, boost.geometry, boost.serialization, boost.spirit) have been updated in this PR. Please review the changes.

**Comment by wep21** [comment]
@bazel-io skip_check unstable_url

**Review by Vertexwahn — DISMISSED** [review]

**Review by bazel-io — DISMISSED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Review by Vertexwahn — DISMISSED** [review]

**Review by bazel-io — DISMISSED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Comment by wep21** [comment]
@fmeum @meteorcloudy @Wyverald Windows tests are failing due to unrelated error.

**Review by meteorcloudy — APPROVED** [review]

**Pull request merged**
