### PR TITLE
realm/SwiftLint@0.52.1

### PR DESCRIPTION
**Pull request by jpsim**
https://github.com/realm/SwiftLint/releases/tag/0.52.1

Signed-off-by: JP Simard <jp@jpsim.com>

### CODE REVIEW

**Review by keith — APPROVED** [review]

**Comment by jpsim** [comment]
Could someone please approve the CI run? Thanks!

**Comment by keith** [comment]
ah sorry i thought it would run automatically

**Comment by jpsim** [comment]
Sorry to bug again, but CI is green and I believe this can now be merged.

**Comment by keith** [comment]
no bother! i should have done automerge

**Comment by jpsim** [comment]
Thanks Keith!

**Pull request merged**
