### PR TITLE
catch2@3.7.0

### PR DESCRIPTION
**Pull request by Vertexwahn**
There is a new release available https://github.com/catchorg/Catch2/releases/tag/v3.7.0

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @curoky, modules you maintain (catch2) have been updated in this PR. Please review the changes.

**Comment by Vertexwahn** [comment]
Need `skip-url-stability-check` label.

**Comment by Vertexwahn** [comment]
@meteorcloudy Can you add the `skip-url-stability-check` label?
@curoky Can you approve?

**Review by curoky — APPROVED** [review]

**Review by fmeum — DISMISSED** [review]

**Review by bazel-io — DISMISSED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Comment by Vertexwahn** [comment]
@curoky Once again please ;)

**Comment by Vertexwahn** [comment]
@curoky I added also Catch 3.7.1

**Review by curoky — APPROVED** [review]

**Review by bazel-io — APPROVED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Pull request merged**
