### PR TITLE
Add glm

### PR DESCRIPTION
**Pull request by Vertexwahn**
Add glm

### CODE REVIEW

**Review by fmeum — APPROVED** [review]

**Comment by phaedon** [comment]
Great, just noticed this! Thanks for setting this up.
I think we might need however:
`includes = ['.'],`

I'm using this as a dependency for [Polyscope](https://polyscope.run/) and with this bzlmod rule, Polyscope compilation fails with:
```
In file included from external/polyscope/deps/MarchingCubeCpp/src/MC_impl.cpp:3:
bazel-out/k8-fastbuild/bin/external/polyscope/deps/MarchingCubeCpp/_virtual_includes/marching_cube/MarchingCube/MC.h:8:10: fatal error: glm/glm.hpp: No such file or directory
    8 | #include <glm/glm.hpp>
```

Thoughts?

**Comment by Vertexwahn** [comment]
@phaedon 

If you are sure that your way of including it (or Polyscopes way) is the right/official/most accepted way to include glm we can change it  - please provide a PR - copy the folder modules/glm/0.9.9.8 and name your folder modules/glm/0.9.9.8.bcr.1 - fix the include issue in the *.bcr.1 folder

**Comment by Vertexwahn** [comment]
@phaedon 

Just checked it again  

Code such as 

```
#include <glm/vec3.hpp> // glm::vec3
#include <glm/vec4.hpp> // glm::vec4
#include <glm/mat4x4.hpp> // glm::mat4
#include <glm/ext/matrix_transform.hpp> // glm::translate, glm::rotate, glm::scale
#include <glm/ext/matrix_clip_space.hpp> // glm::perspective
#include <glm/ext/scalar_constants.hpp> // glm::pi

glm::mat4 camera(float Translate, glm::vec2 const& Rotate)
{
	glm::mat4 Projection = glm::perspective(glm::pi<float>() * 0.25f, 4.0f / 3.0f, 0.1f, 100.f);
	glm::mat4 View = glm::translate(glm::mat4(1.0f), glm::vec3(0.0f, 0.0f, -Translate));
	View = glm::rotate(View, Rotate.y, glm::vec3(-1.0f, 0.0f, 0.0f));
	View = glm::rotate(View, Rotate.x, glm::vec3(0.0f, 1.0f, 0.0f));
	glm::mat4 Model = glm::scale(glm::mat4(1.0f), glm::vec3(0.5f));
	return Projection * View * Model;
}
```

Should compile without changes - so the module is currently wrong - please provide a PR for a bcr.1 version (this is the standard procedure - bcr.1 will take precedence - was done for instance for zlib for your reference)

**Comment by Vertexwahn** [comment]
@phaedon - Just create a PR to fix this -> https://github.com/bazelbuild/bazel-central-registry/pull/1310

**Comment by Vertexwahn** [comment]
@phaedon Fell free to add yourself as a module maintainer for `glm`

**Comment by phaedon** [comment]
Thanks so much for the quick fix! 🔥

**Pull request merged**
