### PR TITLE
re2@2022-06-01

### PR DESCRIPTION
**Pull request by mmorel-35**
Add re2@2022-06-01

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @junyer, modules you maintain (re2) have been updated in this PR. Please review the changes.

**Comment by junyer** [comment]
Please explain **_why_** this is needed. I'm unaware of any technical reason to do this.

**Comment by mmorel-35** [comment]
Some repositories depends on this version this will help migrate to bzlmod without changing the used version

**Comment by junyer** [comment]
Does using an existing version actually cause a build breakage? Also, due to the way that version resolution works in Bzlmod, any other module (i.e. within a given root module's transitive closure of dependencies) can cause a newer version to be used anyway. `grpc` `1.56.3.bcr.1` depends on [`re2` `2021-09-01`](https://github.com/bazelbuild/bazel-central-registry/blob/976deb41655f108f3c61b84fb1b030eba1185b6d/modules/grpc/1.56.3.bcr.1/MODULE.bazel#L14) and [`googletest` `1.14.0.bcr.1`](https://github.com/bazelbuild/bazel-central-registry/blob/976deb41655f108f3c61b84fb1b030eba1185b6d/modules/grpc/1.56.3.bcr.1/MODULE.bazel#L20), for example, but `googletest` `1.14.0.bcr.1` depends on [`re2` `2023-09-01`](https://github.com/bazelbuild/bazel-central-registry/blob/976deb41655f108f3c61b84fb1b030eba1185b6d/modules/googletest/1.14.0.bcr.1/MODULE.bazel#L10), so `re2` `2023-09-01` is what's used. It seems unlikely to me that "backfilling" older versions into BCR would ever be truly necessary.

**Comment by mmorel-35** [comment]
Thank you for the explanations. I'm quite new to bzlmod. I believed it was just better to not do two changes at the same time (switch to bzlmod and update the version of a dependency) but seems it would happen anyway due to the other dependencies of a projet.
This PR looks pointless now.

**Pull request closed without merging**
