### PR TITLE
lowercase imath + openexr changes

### PR DESCRIPTION
**Pull request by asa**
imath deps in bazel are lowercased.
include paths updated to include the parent directory of "Imath" so that `include <Imath/foo.h` works.

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (imath, openexr) have been updated in this PR. Please review the changes.

**Comment by asa** [comment]
Ah, looks like I didn't catch that you can't modify existing versions. Need to bump this version and redo this.

**Comment by bazel-io** [comment]
Hello @asa, too many modules have been updated in this PR. If this is intended, please consider breaking it down into multiple PRs.

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (robin-map) have been updated in this PR. Please review the changes.

**Pull request closed without merging**
