### PR TITLE
Improve opentelemetry-cpp

### PR DESCRIPTION
**Pull request by mering**
- Remove `single_version_override()` which has no effect for foreign modules
- Remove transitive dependencies `upb` and `zlib`

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @keith, modules you maintain (opentelemetry-cpp) have been updated in this PR. Please review the changes.

**Comment by mering** [comment]
@fmeum could you please trigger the tests?

**Comment by keith** [comment]
see also upstream work here https://github.com/open-telemetry/opentelemetry-cpp/pull/2608/files

**Comment by mering** [comment]
@keith Can we still merge this until the upstream work will be available in a new version?

**Comment by keith** [comment]
can you point to where rules_go is used upstream? the "unused" dependencies were about making sure we had specific versions

**Comment by mering** [comment]
> can you point to where rules_go is used upstream? the "unused" dependencies were about making sure we had specific versions

I don't know but when I was building the targets from a foreign module, it failed with missing `rules_go`.

**Comment by mering** [comment]
The `upb` dependency is definitely not necessary and breaks our module when forcing an upgrade. Without this, everything works fine. So I would definitely prefer not to have these unused dependencies specified.

**Comment by keith** [comment]
can you post the errors you're seeing? upb comes through rules_python -> protobuf

**Comment by mering** [comment]
The tests hier agree that not forcing an `upb` upgrade doesn't break anything. Since `upb` is not used by `opentelemetry-cpp` directly, it would be a bug in the dependencies when they specify a too old version, no?

I removed the dependency to `rules_go` in this PR as doesn't seem to be used directly. Specifying transitive dependencies in `MODULE.bazel` is an anti-pattern though and I would really like if we could merge this to unblock us migrating this dependency to Bzlmod.

**Comment by fmeum** [comment]
@keith LGTM, do you want to merge this?

**Review by keith — APPROVED** [review]
whatever i added upb for seems to have gone away, maybe with a grpc update. note that zlib will be back in the next version since there is a direct dependency on it upstream now.

**Pull request merged**
