### PR TITLE
libxml2@2.13.5 (#2511)

### LINKED ISSUE #2511: wanted: [GNOME/libxml2]
### Module location

https://gitlab.gnome.org/GNOME/libxml2

### Link to bzlmod issue in the module's repository

_No response_

### Any other context to provide?

Previous stale PR #282

### Fund our work

- [ ] Sponsor our community's open source work by donating a [feature bounty](https://opencollective.com/bazel-rules-authors-sig/projects/bazel-central-registry)

### PR DESCRIPTION
**Pull request by dmitry-j-mikhin**
Closes #2511

Release: https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.13.5

Previous stale PR #282

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (libxml2) have been updated in this PR. Please review the changes.

**Review by meteorcloudy — APPROVED** [review]

**Comment by dmitry-j-mikhin** [comment]
@meteorcloudy thanks for approval, I will try to fix failed checks.

**Comment by dmitry-j-mikhin** [comment]
The issue seems to only exist on Windows in rules_foreign_cc during toolchain resolution.

**Comment by bazel-io** [comment]
Hello @jsharpe, modules you maintain (rules_foreign_cc) have been updated in this PR. Please review the changes.

**Comment by dmitry-j-mikhin** [comment]
@meteorcloudy @jsharpe looks like I fixed the Windows build.
Now all the checkmarks are green. https://github.com/dmitry-j-mikhin/rules_foreign_cc/commit/a2d3edf9e676442b67d9aeaee142f041f0579b3d - this commit fixes the execution of rules_foreign_cc on Win with bzlmod.
I'll be on vacation next week, so I can prepare clean PRs after that.

**Comment by bazel-io** [comment]
Hello @jsharpe, modules you maintain (rules_foreign_cc) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (libxml2) have been updated in this PR. Please review the changes.

**Review by jsharpe — CHANGES_REQUESTED** [review]
The problem with this point fix to 0.11.1 is it's lost with 0.12.0, can you instead issue a PR to the main repo for rules_foreign_cc so we can verify it passes the tests and we can then get a proper release version to support this.

**Comment by dmitry-j-mikhin** [comment]
> The problem with this point fix to 0.11.1 is it's lost with 0.12.0, can you instead issue a PR to the main repo for rules_foreign_cc so we can verify it passes the tests and we can then get a proper release version to support this.

Yep, I'm working on it.

**Comment by dmitry-j-mikhin** [comment]
@jsharpe clean PR based on 0.12.0 here - https://github.com/bazelbuild/rules_foreign_cc/pull/1264, I think it should be merged first, and then I can refactor the current PR to BCR. Right now the PR in BCR is based on my testing release - https://github.com/dmitry-j-mikhin/rules_foreign_cc/releases/tag/0.12.1-fix1239, it should be switched to the official rules_foreign_cc release.

**Comment by dmitry-j-mikhin** [comment]
The `0.13.0` release of [`rules_foreign_cc`](https://github.com/bazel-contrib/rules_foreign_cc/releases/tag/0.13.0) includes the changes from [PR #1264](https://github.com/bazel-contrib/rules_foreign_cc/pull/1264).  
I’ll update this PR to use the official release, allowing the draft tag to be removed.

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (libxml2) have been updated in this PR. Please review the changes.

**Comment by dmitry-j-mikhin** [comment]
The CI is now passing successfully, including Windows! 🎉 I've removed the draft tag.  
  
@meteorcloudy, @jsharpe — Could you please review the changes when you have time? 😊

**Review by jsharpe — APPROVED** [review]
LGTM

**Review by fmeum — APPROVED** [review]

**Pull request merged**
