### PR TITLE
Add bazel_features 1.7.0

### PR DESCRIPTION
**Pull request by fmeum**

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @Wyverald, @meteorcloudy, modules you maintain (bazel_features) have been updated in this PR. Please review the changes.

**Comment by fmeum** [comment]
The BCR app failed to publish this version.

**Review by meteorcloudy — APPROVED** [review]

**Comment by meteorcloudy** [comment]
> The BCR app failed to publish this version.

/cc @kormide

**Comment by kormide** [comment]
This was a rare type of failure. GCP didn't have enough resources at the time to service the cloud function.

**Comment by fmeum** [comment]
I messed up the manual release. I now triggered an automatic release with the tag v1.7.1 that is otherwise identical. Afterwards we can yank v1.7.0.

**Comment by meteorcloudy** [comment]
Ah,, sorry for missing that in the review.

**Pull request merged**
