### PR TITLE
feat: add suitesparse amd

### PR DESCRIPTION
**Pull request by wep21**
add [suitesparse amd](https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v7.6.0)

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (suitesparse) have been updated in this PR. Please review the changes.

**Comment by wep21** [comment]
Needs skip url stability check

**Comment by meteorcloudy** [comment]
Please address the windows failure.

**Comment by wep21** [comment]
@meteorcloudy drop windows ci because suitesparse only supports posix

**Review by meteorcloudy — APPROVED** [review]

**Pull request merged**
