### PR TITLE
Add SwiftLint 0.55.1

### PR DESCRIPTION
**Pull request by SimplyDanny**

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @jpsim, modules you maintain (swiftlint) have been updated in this PR. Please review the changes.

**Review by jpsim — APPROVED** [review]
Thanks!

**Review by bazel-io — DISMISSED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Comment by meteorcloudy** [comment]
@SimplyDanny Can you rebase your branch to BCR HEAD to resolve the presubmit failure?

**Comment by bazel-io** [comment]
Hello @jpsim, modules you maintain (swiftlint) have been updated in this PR. Please review the changes.

**Review by meteorcloudy — APPROVED** [review]

**Pull request merged**
