### PR TITLE
Add nanobind_bazel v2.2.0

### PR DESCRIPTION
**Pull request by nicholasjng**
Contains nanobind v2.2.0, with free-threading support in Python 3.13+.

### CODE REVIEW

**Comment by nicholasjng** [comment]
Hm, guess something in my deps dropped Bazel 6.x already.

**Comment by nicholasjng** [comment]
Pretty sure it's `rules_cc`, which is tested under Bazel 7.x only since 0.0.10.

How do I go about this? Rerelease with a downgraded `rules_cc`, or drop Bazel 6 altogether?

**Comment by fmeum** [comment]
Since Bzlmod uses Minimum Version Selection, you are generally encouraged to keep the version requirements of library projects as low as possible. That would probably solve the failure in this case.

**Comment by nicholasjng** [comment]
Makes sense. I think I'll close this, as I would also like to grab Python 3.13 support from the newly released `rules_python@0.37.0` for nanobind+CPython3.13 builds.

**Pull request closed without merging**
