### PR TITLE
Add protoc-gen-validate 1.1.0

### PR DESCRIPTION
**Pull request by mering**

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (protoc-gen-validate) have been updated in this PR. Please review the changes.

**Comment by mering** [comment]
@bazel-io skip_check unstable_url

**Comment by keith** [comment]
ci failure

**Comment by mering** [comment]
@keith can you trigger the CI again please?

**Comment by mering** [comment]
@keith one more time please

**Comment by mering** [comment]
@keith Do you have an idea on how to break the dependency cycle?

**Comment by keith** [comment]
i'd have to look deeper. i imagine there are some issues about it out there. i've been working on parts of this upstream, would be nice if we could land it there

**Comment by mering** [comment]
Reported an issue in https://github.com/bazel-contrib/rules_go/issues/4196.

**Pull request closed without merging**
