### PR TITLE
libarchive 3.7.4.bcr.3; add patch to set HAVE_ZSTD_compressStream

### PR DESCRIPTION
**Pull request by ewhauser**
This patch sets the `HAVE_ZSTD_compressStream` flag to `1` so that `tar` will use a statically linked `zstd` when compressing archives. See https://github.com/aspect-build/bazel-lib/pull/878#issuecomment-2225981766 for more details on why this behavior is desired.

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @dzbarsky, @zaucy, modules you maintain (libarchive) have been updated in this PR. Please review the changes.

**Comment by zaucy** [comment]
Am i right to say this is the only change in the patch? https://github.com/zaucy/libarchive/commit/101b2b5103617768d340904301080956afde4d60 I maintain a fork that I'm attempting to keep up to date with whats on the BCR.

**Comment by ewhauser** [comment]
Correct

```
$ diff 3.7.4.bcr.2/patches/build_with_bazel.patch 3.7.4.bcr.3/patches/build_with_bazel.patch
52c52
< index 00000000..fafe8e7a
---
> index 00000000..85f1e7ba
58c58
< +    version = "3.7.4.bcr.2",
---
> +    version = "3.7.4.bcr.3",
1350c1350
< index 00000000..c998c9f0
---
> index 00000000..1d41dc3e
1353c1353
< @@ -0,0 +1,187 @@
---
> @@ -0,0 +1,188 @@
1511a1512
> +#define HAVE_ZSTD_compressStream 1
```

**Review by zaucy — APPROVED** [review]
We've tested this patch on our projects and it's good for us :+1:

**Comment by DavidZbarsky-at** [comment]
This patch was my suggestion, I approve :)

**Review by bazel-io — APPROVED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Comment by alexeagle** [comment]
@zaucy sorry did we miss some PRs that you needed on your fork?

**Comment by zaucy** [comment]
Nope you're good! That was #2271 which was the patch prior to this one. I was only asking the PR author because I want to make sure my fork is up to date when I inevitably make another patch.

**Pull request merged**
