### PR TITLE
Add swift-indexstore

### PR DESCRIPTION
**Pull request by ileitch**

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (swift-indexstore) have been updated in this PR. Please review the changes.

**Review by keith — APPROVED** [review]

**Comment by keith** [comment]
Enabled auto merge

**Comment by ileitch** [comment]
@keith Buildkite appears to not have noticed your approval

**Comment by keith** [comment]
i must have misclicked, sorry about that, did it again

**Pull request merged**
