### PR TITLE
rules_bison@0.3

### PR DESCRIPTION
**Pull request by jmillikin**
Release: https://github.com/jmillikin/rules_bison/releases/tag/v0.3

### CODE REVIEW

**Review by fmeum — DISMISSED** [review]

**Comment by jmillikin** [comment]
Ah, Bazel v6 Turbine crashes, we meet again.

Added `bazel_dep(name = "rules_java", version = "6.0.0")` in a patch as a workaround.

**Review by fmeum — APPROVED** [review]

**Comment by jmillikin** [comment]
I've undone the commit with the `rules_java` workaround since it doesn't seem to be effective this time.

Filed https://github.com/bazelbuild/bazel-central-registry/issues/2905 to see about getting the BCR CI scripts fixed so that it runs Bazel 6.x builds with a version of Java that is compatible with their toolchains.

**Comment by jmillikin** [comment]
The changes to https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/bazel-central-registry/bcr_presubmit.py needed for fixing the Java 21 <-> Bazel 6.x incompatibility were more than I'm prepared to attempt at this time.

Changed this module's presubmit to `bazel: ["7.x"]`.

**Comment by jmillikin** [comment]
Looks like tests are green now! @fmeum , could I ask for your review?

**Review by fmeum — APPROVED** [review]

**Pull request merged**
