### PR TITLE
feat: update boost

### PR DESCRIPTION
**Pull request by wep21**
- also closes #3159

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.multi_index) have been updated in this PR. Please review the changes.

**Comment by wep21** [comment]
@bazel-io skip_check unstable_url

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.multi_index, boost.property_map) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.bimap, boost.multi_index, boost.property_map) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.bimap, boost.foreach, boost.multi_index, boost.property_map) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.bimap, boost.foreach, boost.multi_index, boost.property_map, boost.property_tree) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.bimap, boost.foreach, boost.lambda, boost.multi_index, boost.property_map, boost.property_tree) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.bimap, boost.foreach, boost.lambda, boost.multi_index, boost.property_map, boost.property_tree, boost.xpressive) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.bimap, boost.foreach, boost.format, boost.lambda, boost.multi_index, boost.property_map, boost.property_tree, boost.xpressive) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.bimap, boost.foreach, boost.format, boost.graph, boost.lambda, boost.multi_index, boost.property_map, boost.property_tree, boost.xpressive) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.bimap, boost.circular_buffer, boost.foreach, boost.format, boost.graph, boost.iostreams, boost.json, boost.lambda, boost.multi_index, boost.property_map, boost.property_tree, boost.xpressive) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.bimap, boost.circular_buffer, boost.foreach, boost.format, boost.graph, boost.iostreams, boost.json, boost.lambda, boost.logic, boost.multi_index, boost.property_map, boost.property_tree, boost.xpressive) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.bimap, boost.circular_buffer, boost.foreach, boost.format, boost.graph, boost.iostreams, boost.json, boost.lambda, boost.logic, boost.multi_array, boost.multi_index, boost.property_map, boost.property_tree, boost.xpressive) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.bimap, boost.circular_buffer, boost.foreach, boost.format, boost.graph, boost.iostreams, boost.json, boost.lambda, boost.logic, boost.multi_array, boost.multi_index, boost.pfr, boost.property_map, boost.property_tree, boost.xpressive) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.bimap, boost.circular_buffer, boost.foreach, boost.format, boost.graph, boost.iostreams, boost.json, boost.lambda, boost.logic, boost.multi_array, boost.multi_index, boost.pfr, boost.program_options, boost.property_map, boost.property_tree, boost.ptr_container, boost.xpressive) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.bimap, boost.circular_buffer, boost.foreach, boost.format, boost.graph, boost.iostreams, boost.json, boost.lambda, boost.logic, boost.multi_array, boost.multi_index, boost.pfr, boost.program_options, boost.property_map, boost.property_tree, boost.ptr_container, boost.sort, boost.static_string, boost.xpressive) have been updated in this PR. Please review the changes.

**Review by Vertexwahn — APPROVED** [review]

**Review by bazel-io — DISMISSED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Review by Vertexwahn — APPROVED** [review]

**Review by bazel-io — APPROVED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Pull request merged**
