### PR TITLE
feat: update boost.geometry

### PR DESCRIPTION
**Pull request by wep21**
- as title

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.any) have been updated in this PR. Please review the changes.

**Comment by wep21** [comment]
@bazel-io skip_check unstable_url

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.any, boost.polygon) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.any, boost.polygon, boost.qvm) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.any, boost.multiprecision, boost.polygon, boost.qvm) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.any, boost.multiprecision, boost.polygon, boost.proto, boost.qvm) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.any, boost.endian, boost.multiprecision, boost.polygon, boost.proto, boost.qvm) have been updated in this PR. Please review the changes.

**Comment by bazel-io** [comment]
Hello @Vertexwahn, modules you maintain (boost.any, boost.endian, boost.multiprecision, boost.phoenix, boost.polygon, boost.proto, boost.qvm) have been updated in this PR. Please review the changes.

**Review by bazel-io — APPROVED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Pull request merged**
