### PR TITLE
fix: compatibility level default in add_module.py

### PR DESCRIPTION
**Pull request by cgrindel**
The default compatibility level value should be 0, not 1.

### CODE REVIEW

**Comment by cgrindel** [comment]
@fmeum I started to update the code to not write the compatibility level if it is 0. However, I noticed that there are no tests for this script or its Python modules. I don't feel comfortable making this change without any existing tests and I don't have the time or inclination to implement them. Can we proceed with this minimal change for now?

**Comment by fmeum** [comment]
Sounds good, thanks for trying!

**Review by fmeum — DISMISSED** [review]
Cc @meteorcloudy

**Comment by cgrindel** [comment]
@fmeum Unfortunately, I do not have permission to merge. Would you mind hitting the button?

**Review by fmeum — APPROVED** [review]

**Pull request merged**
