### PR TITLE
apple_rules_lint: add gibfahn as maintainer

### PR DESCRIPTION
**Pull request by gibfahn**
---

#### Commits _(oldest to newest)_

9a9ff501 apple_rules_lint: add gibfahn as maintainer

<br/>

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @@shs96c, modules you maintain (apple_rules_lint) have been updated in this PR. Please review the changes.

**Review by shs96c — APPROVED** [review]
LGTM

**Review by bazel-io — APPROVED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Review by shs96c — APPROVED** [review]
LGTM

**Pull request merged**
