### PR TITLE
Add grpc 1.63.1

### PR DESCRIPTION
**Pull request by bentekkie**
Patches are mostly the same as 1.62.1 just rebased. Added new rules_apple and google_benchmark dependencies

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (grpc) have been updated in this PR. Please review the changes.

**Comment by bentekkie** [comment]
I am seeing
```

grpc@1.63.1 is using an unstable source url: `https://github.com/grpc/grpc/archive/refs/tags/v1.63.1.tar.gz`.
--
  | You should use a release archive URL in the format of `https://github.com/<ORGANIZATION>/<REPO>/releases/download/<version>/<name>.tar.gz` to ensure the archive checksum stability.
  | See https://blog.bazel.build/2023/02/15/github-archive-checksum.html for more context.

```

But there is no archive like that available from grpc

**Comment by bentekkie** [comment]
Tests pass! Let me know what else is needed to get this submitted

**Comment by Wyverald** [comment]
> Patches are mostly the same as 1.62.1 just rebased. Added new rules_apple and google_benchmark dependencies

have you incorporated the patches in 1.62.1.bcr.2 (see https://github.com/bazelbuild/bazel-central-registry/blob/main/modules/grpc/1.62.1.bcr.2/source.json)? or have they been upstreamed?

**Comment by bentekkie** [comment]
I incorporated all patches from 1.62.1 1.62.1.bcr.1 and 1.62.1.bcr.2. I combined all non MODULE.bazel patches into one patch file.

**Comment by bentekkie** [comment]
Let me double check

**Comment by bentekkie** [comment]
Verifed that all patches from 1.62.1, 1.62.1.bcr.1 and 1.62.1.bcr.2 have been brought forward or upstreamed.

I updated the presubmit test to run on mac and windows again (this was removed in 1.62.bcr.2)
`@grpc//examples/protos/...` only builds on ci on linux. For windows it seems that grpc is expecting a msys/mingw toolchain and for mac there are some missing `_PyBytes_` objects for cython. Fixing these seems out of scope for importing the new grpc version as these breakages seem present for 1.62.1 aswell

**Review by fmeum — APPROVED** [review]

**Pull request merged**
