### PR TITLE
Add riegeli 0.0.0-20240927-cdfb25a

### PR DESCRIPTION
**Pull request by mering**

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @QrczakMK, modules you maintain (riegeli) have been updated in this PR. Please review the changes.

**Comment by mering** [comment]
@meteorcloudy @fmeum could you please trigger the tests? Thanks!

**Review by QrczakMK — DISMISSED** [review]

**Review by QrczakMK — DISMISSED** [review]

**Review by bazel-io — DISMISSED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Comment by mering** [comment]
@meteorcloudy could you PTAL? Thanks!

**Review by meteorcloudy — APPROVED** [review]

**Pull request merged**
