### PR TITLE
Add swift-filename-matcher

### PR DESCRIPTION
**Pull request by ileitch**

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (swift-filename-matcher) have been updated in this PR. Please review the changes.

**Review by keith — DISMISSED** [review]

**Comment by keith** [comment]
CI failure

**Review by keith — APPROVED** [review]

**Comment by keith** [comment]
i think you need https://github.com/bazelbuild/bazel-central-registry/pull/2661#issuecomment-2308323732

**Review by keith — APPROVED** [review]

**Comment by keith** [comment]
Enabled auto merge

**Pull request merged**
