### PR TITLE
Fix empty glob in boost.bimap .multi_index .serialization

### PR DESCRIPTION
**Pull request by hofbi**

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @wep21, @Vertexwahn, modules you maintain (boost.bimap, boost.multi_index, boost.serialization) have been updated in this PR. Please review the changes.

**Review by Vertexwahn — APPROVED** [review]

**Review by bazel-io — APPROVED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Comment by Wyverald** [comment]
boost.lambda@1.83.0.bcr.1 doesn't seem to exist.

**Comment by wep21** [comment]
boost.serialization has been already updated.

**Comment by meteorcloudy** [comment]
Please rebase this PR

**Pull request closed without merging**
