### PR TITLE
Add RE2 release `2023-06-02`.

### PR DESCRIPTION
**Pull request by junyer**
Ping, @meteorcloudy? :)

### CODE REVIEW

**Review by fmeum — APPROVED** [review]

**Comment by fmeum** [comment]
@junyer In case you have a chance to influence this: It would be great if upstream could publish release artifacts as the current source URL is not guaranteed to provide a consistent hash over time.

**Comment by junyer** [comment]
> @junyer In case you have a chance to influence this: It would be great if upstream could publish release artifacts as the current source URL is not guaranteed to provide a consistent hash over time.

My understanding was that the issue had been resolved as per https://github.com/bazelbuild/bazel-central-registry/issues/69. Is that not actually the case? :(

**Comment by junyer** [comment]
Looking at the failed checks, I see that I totally forgot to configure dependencies on Abseil and GoogleTest. (Benchmark isn't in BCR, so I will have to exclude one of our targets.)

**Comment by fmeum** [comment]
> My understanding was that the issue had been resolved as per #69. Is that not actually the case? :(

We thought so too, but it turned out that this was just miscommunication on GitHub's part and these links also aren't stable (see the rest of https://github.com/bazel-contrib/SIG-rules-authors/issues/11 for all the details). The only stable artifacts are manually created release artifacts.

**Comment by junyer** [comment]
Unfortunately, I don't understand why the checks are now barfing on `MODULE.bazel`. Could someone please let me know?

**Comment by junyer** [comment]
> We thought so too, but it turned out that this was just miscommunication on GitHub's part and these links also aren't stable (see the rest of https://github.com/bazel-contrib/SIG-rules-authors/issues/11 for all the details). The only stable artifacts are manually created release artifacts.

I wonder whether https://code.googlesource.com/re2 can guarantee stability. 🤔

**Comment by junyer** [comment]
FYI, I made `compatibility_level` match the current `SONAME`.

**Comment by junyer** [comment]
I formatted `MODULE.bazel` and that rearranged things a bit more than I was expecting, but c'est la vie.

**Comment by fmeum** [comment]
My bad, forgot that the BCR doesn't test modules as root modules. If you want to run the tests, you will need to remove the `dev_dependency` param on the `googletest` dep.

**Comment by junyer** [comment]
> My bad, forgot that the BCR doesn't test modules as root modules. If you want to run the tests, you will need to remove the `dev_dependency` param on the `googletest` dep.

No worries. Done. :)

**Comment by junyer** [comment]
RE2 recently started doing [this](https://github.com/google/re2/blob/7c5e396af825562ec8321fdbf2f1cf276b26e3ae/.bazelrc#L5-L13) to unbreak the Bazel CI, but I'm not sure what to do for the BCR CI...

**Pull request merged**
