### PR TITLE
Add rules_erlang 2.5.1

### PR DESCRIPTION
**Pull request by pjk25**
Add the most recent release of https://github.com/rabbitmq/rules_erlang

### CODE REVIEW

**Comment by pjk25** [comment]
I may be reading them incorrectly, but it appears to me from the logs of the above checks that the github mirroring using in the checks did not work correctly?

**Comment by meteorcloudy** [comment]
No, the warning will go away after this PR is merged, the real issue is:
```
(11:26:39) ERROR: Analysis of target '@rules_erlang.2.5.1//shard_suite:erlang_app' failed; build aborted: no such package '@rules_erlang.2.5.1//private': The repository '@rules_erlang.2.5.1' could not be resolved: Repository '@rules_erlang.2.5.1' is not visible from repository '@rules_erlang.2.5.1'
```

**Comment by pjk25** [comment]
> No, the warning will go away after this PR is merged, the real issue is:
> 
> ```
> (11:26:39) ERROR: Analysis of target '@rules_erlang.2.5.1//shard_suite:erlang_app' failed; build aborted: no such package '@rules_erlang.2.5.1//private': The repository '@rules_erlang.2.5.1' could not be resolved: Repository '@rules_erlang.2.5.1' is not visible from repository '@rules_erlang.2.5.1'
> ```

Thanks @meteorcloudy. I haven't been able to reproduce that error locally, even with adding a `MODULE.bazel` in `rules_erlang/test` as follows:

```starlark
module(
    name = "rules_erlang_test",
    version = "0.1.0",
)

bazel_dep(
    name = "rules_erlang",
    version = "2.5.1",
)

local_path_override(
    module_name = "rules_erlang",
    path = "..",
)
```

and running `bazelisk test @rules_erlang//...` from that directory.

It's difficult for me to understand the error since this passed with `rules_erlang@2.4.0` and the structure doesn't seem to have changed in any important way. Do you have any further insight into the error message?

**Comment by Wyverald** [comment]
It's a new change in rules_erlang that makes it incompatible with bzlmod: [this line](https://github.com/rabbitmq/rules_erlang/blob/dbba9b5b0f76f232c24da84621215a200ac4fc58/app_file.bzl#L3) needs to be fixed to not include `str(...)`

**Comment by pjk25** [comment]
> It's a new change in rules_erlang that makes it incompatible with bzlmod: [this line](https://github.com/rabbitmq/rules_erlang/blob/dbba9b5b0f76f232c24da84621215a200ac4fc58/app_file.bzl#L3) needs to be fixed to not include `str(...)`

Thanks @Wyverald , this would have taken me forever to figure out myself.

**Comment by Wyverald** [comment]
Yeah, that's obviously not great 😅 we really need to think about how we could improve the error messaging here.

**Comment by pjk25** [comment]
I will fix this in rules_erlang 2.5.2, and open a new corresponding PR.

**Pull request closed without merging**
