### PR TITLE
google_benchmark@1.8.4

### PR DESCRIPTION
**Pull request by Vertexwahn**
Add google_benchmark@1.8.4

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (google_benchmark) have been updated in this PR. Please review the changes.

**Comment by Vertexwahn** [comment]
Need `skip-url-stability-check` label.

**Comment by Vertexwahn** [comment]
I copied the MODULE.bazel file from google benchmark - it contains:

```
python.toolchain(
    is_default = True,
    python_version = "3.12",
)
```

not sure if this has any side effects...

**Comment by fmeum** [comment]
It's a dev dependency, so we don't need to worry about what it does

**Review by fmeum — APPROVED** [review]

**Pull request merged**
