### PR TITLE
Add SourceKitten 0.35.0

### PR DESCRIPTION
**Pull request by SimplyDanny**

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @jpsim, @keith, modules you maintain (sourcekitten) have been updated in this PR. Please review the changes.

**Comment by keith** [comment]
needs a presubmit update to include the bazel version

**Comment by keith** [comment]
needs the toolchain env var workaround too

**Review by keith — APPROVED** [review]

**Review by bazel-io — APPROVED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Pull request merged**
