### PR TITLE
Add rules_go 0.39.1

### PR DESCRIPTION
**Pull request by fmeum**
Published manually as a typo in the source archive name caused the Publish to BCR action to fail.

### CODE REVIEW

**Comment by fmeum** [comment]
FYI @tyler-french

**Comment by fmeum** [comment]
@meteorcloudy CI is failing because a shell script in the source archive isn't executable, but the permissions in the ZIP look correct. Is it possible that the registry infra loses these permissions somewhere?

**Comment by meteorcloudy** [comment]
Hmm, maybe it's something wrong here: https://github.com/bazelbuild/continuous-integration/blob/e473c2e1634b8883ff96915afbfc3046fa4c5694/buildkite/bazel-central-registry/bcr_presubmit.py#L214

**Comment by meteorcloudy** [comment]
I can look into this tomorrow, in the meantime, maybe you can use a [shell command](https://github.com/bazelbuild/continuous-integration/tree/master/buildkite#running-commands-shell-scripts-or-binary-targets) to fix the permission?

**Review by tyler-french — APPROVED** [review]

**Comment by meteorcloudy** [comment]
Regarding the file permission issue, the bug has been reported before: https://github.com/bazelbuild/continuous-integration/issues/1536, sending a fix now

**Pull request merged**
