### PR TITLE
rules_jvm_external 6.5

### PR DESCRIPTION
**Pull request by shs96c**

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @jin, @cheister, modules you maintain (rules_jvm_external) have been updated in this PR. Please review the changes.

**Review by jin — DISMISSED** [review]
Thanks!

**Review by jin — APPROVED** [review]

**Review by bazel-io — APPROVED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Comment by meteorcloudy** [comment]
Looks like https://github.com/bazelbuild/bazel-central-registry/pull/3059 is causing trouble in presubmit, I'll revert that change for now.

**Comment by mattyclarkson** [comment]
> Looks like #3059 is causing trouble in presubmit, I'll revert that change for now.

Sorry, my bad. #3072 fixes.

**Review by meteorcloudy — APPROVED** [review]

**Pull request merged**
