### PR TITLE
Add rules_testing to BCR

### PR DESCRIPTION
**Pull request by rickeylev**
cc @comius

### CODE REVIEW

**Comment by keith** [comment]
looks like the failures here are real

**Comment by rickeylev** [comment]
Ok, fixed, I think; I guess we'll see what CI says.

Couple questions:
* Are the files under the versioned directory still needed if bazelbuild/rules_testing is already setup with BCR pushing? Or can we simply add the metadata.json file? [bcr push config](https://github.com/bazelbuild/rules_testing/tree/master/.bcr)
* I _think_ I've got bazelbuild/rules_testing setup with BCR pushing correctly, but it fails with this error:

```
Could not find a candidate bazel-central-registry fork to push to.
Publish to BCR must be installed to a BCR fork in either:
  a) the same account as the ruleset
  b) the release author's account
Install the app here: https://github.com/apps/publish-to-bcr.
```

As far as I can tell, I've done that. So I'm not sure if this error is trying to say "you have to do something in bazel-central-repository first" or if there's some other config thing somewhere I need to do.

**Comment by fmeum** [comment]
@kormide

**Review by fmeum — APPROVED** [review]

**Comment by kormide** [comment]
> Ok, fixed, I think; I guess we'll see what CI says.
> 
> Couple questions:
> 
>     * Are the files under the versioned directory still needed if bazelbuild/rules_testing is already setup with BCR pushing? Or can we simply add the metadata.json file? [bcr push config](https://github.com/bazelbuild/rules_testing/tree/master/.bcr)
> 

The app requires all of the template files. Any changes you make to the metadata file (e.g., updating maintainers) get reflected in the pull request made by the bot.

>     * I _think_ I've got bazelbuild/rules_testing setup with BCR pushing correctly, but it fails with this error:
> 
> 
> ```
> Could not find a candidate bazel-central-registry fork to push to.
> Publish to BCR must be installed to a BCR fork in either:
>   a) the same account as the ruleset
>   b) the release author's account
> Install the app here: https://github.com/apps/publish-to-bcr.
> ```
> 
> As far as I can tell, I've done that. So I'm not sure if this error is trying to say "you have to do something in bazel-central-repository first" or if there's some other config thing somewhere I need to do.

Weird. You've installed the app to `rickeylev/bazel-central-registry`?

**Comment by rickeylev** [comment]
> You've installed the app to rickeylev/bazel-central-registry

Ah, no I had not. I just installed it in bazelbuild/rules_testing. I've installed it now to mine and it looks like it successfully sent a PR. Thanks!

**Pull request merged**
