### PR TITLE
Add gonzojive_protobuf_javascript module.

### PR DESCRIPTION
**Pull request by gonzojive**
Checked with `python3 tools/bcr_validation.py --check=protobuf_javascript_esm`.

The module in question is my fork of the protobuf-javascript repo. The changes in the fork are unlikely to be accepted upstream (see https://github.com/protocolbuffers/protobuf-javascript/pull/156).

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (protobuf_javascript_esm) have been updated in this PR. Please review the changes.

**Comment by meteorcloudy** [comment]
Maybe `protobuf_javascript_gonzojive` is a better name to indicate this is a fork?

**Comment by fmeum** [comment]
Following other examples in the registry, `<org>_protobuf_javascript` would fit well.

**Comment by bazel-io** [comment]
Hello @bazelbuild/bcr-maintainers, modules without existing maintainers (gonzojive_protobuf_javascript) have been updated in this PR. Please review the changes.

**Comment by gonzojive** [comment]
Done.

**Comment by Wyverald** [comment]
please fix check failures.

**Comment by gonzojive** [comment]
I suspect it will work now. I removed debian10 due to a C++ error in protobuf that I'm not sure how to resolve.

**Pull request merged**
