### PR TITLE
Add libarchive 3.7.2.bcr.4

### PR DESCRIPTION
**Pull request by keith**
This adds mbedtls support (controlled by `@libarchive//:use_mbedtls=true` and fixes compatibility with incompatible_disallow_empty_glob

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @dzbarsky, modules you maintain (libarchive) have been updated in this PR. Please review the changes.

**Comment by keith** [comment]
the second commit here shows the diff from the previously checked in patch file

**Comment by keith** [comment]
bumped the xz dep with https://github.com/bazelbuild/bazel-central-registry/pull/1895

**Comment by DavidZbarsky-at** [comment]
If you're shipping a new version, could you please try to bump bzip2? I think that should let us drop the bzlib imports patch

**Comment by keith** [comment]
done, we'll see what CI thinks

**Review by fmeum — APPROVED** [review]

**Pull request merged**
