### PR TITLE
Add SwiftLint 0.56.2

### PR DESCRIPTION
**Pull request by SimplyDanny**
Associated release: https://github.com/realm/SwiftLint/releases/tag/0.56.2

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @jpsim, modules you maintain (swiftlint) have been updated in this PR. Please review the changes.

**Review by jpsim — DISMISSED** [review]

**Review by bazel-io — APPROVED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Comment by keith** [comment]
looks like a failure

**Comment by SimplyDanny** [comment]
`BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1` sounds like it could resolve the failure. Let's see ...

**Review by keith — APPROVED** [review]

**Pull request merged**
