### PR TITLE
Update rules_perl w/ includes attr patch

### PR DESCRIPTION
**Pull request by lalten**
This is latest rules_perl plus
* https://github.com/bazelbuild/rules_perl/pull/62
* https://github.com/bazelbuild/rules_perl/pull/65
* https://github.com/bazelbuild/rules_perl/pull/66

Obviously it would be nice to get a review / merge this upstream. If that still happens we can add a new (0.2.4 ?) release without patches in the BCR.

The patch enables external rules_perl Bazel repos to work under Bzlmod. This is needed for https://github.com/lalten/rules_cpan to work out of the box

needs the `unstable source url` label

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @mortenmj, modules you maintain (rules_perl) have been updated in this PR. Please review the changes.

**Review by mortenmj — APPROVED** [review]
lgtm

**Review by bazel-io — APPROVED** [review]
Hello @bazelbuild/bcr-maintainers, all modules in this PR have been approved by their maintainers. Please take a final look to merge this PR.

**Review by meteorcloudy — DISMISSED** [review]

**Comment by meteorcloudy** [comment]
Please check the presubmit failures

**Review by Wyverald — APPROVED** [review]

**Pull request merged**
