### PR TITLE
feat(rules_diff): add `1.0.0-beta.2`

### PR DESCRIPTION
**Pull request by mattyclarkson**
Apple Silicon support via `ape@1.0.0-beta.2`.

### CODE REVIEW

**Comment by mattyclarkson** [comment]
@fmeum would it be possible to get `pre-submit` for this? Needed to unblock #1868 (`rules_git`)

**Comment by mattyclarkson** [comment]
I'm doing some remote execution fixes to `bazel/ape` that this will need to pick up.

I'll update this once those are ready.

**Comment by mattyclarkson** [comment]
Needs #1926.

**Comment by mattyclarkson** [comment]
Needs #1929.

**Comment by mattyclarkson** [comment]
@fmeum this is ready. All checks passed on CI. Apple Silicon is good. I _assume_ we have a BCR run that does remote execution. We've validated RE on our side though.

**Review by fmeum — APPROVED** [review]

**Pull request merged**
